Repository getlago/lago-front, pull requests merged in 2022-09, with the labels that each got.

#385 fix: 🎬 Truncate company name if too long
  src/layouts/SideNavLayout.tsx
Labels: 🐞 bug

#395 chore: 📝 rename customer and subscription id attributes to match new AP…
  ditto/base.json
  src/components/addOns/AddOnCodeSnippet.tsx
  src/components/billableMetrics/BillableMetricCodeSnippet.tsx
  src/components/coupons/CouponCodeSnippet.tsx
  src/components/customers/AddCustomerDialog.tsx
  src/components/customers/CustomerItem.tsx
  src/components/customers/CustomerMainInfos.tsx
  src/components/customers/subscriptions/CustomerSubscriptionsList.tsx
  src/components/debugger/EventItem.tsx
  src/components/plans/PlanCodeSnippet.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditCustomer.ts
  src/pages/CustomerDetails.tsx
  src/pages/developpers/Debugger.tsx
Labels: 🥷 chore

#398 fix: 🪳 Debug dialog wording
  ditto/base.json
Labels: 🎨 UI

#399 fix: 🫥 Default route customer details
  src/pages/CustomerDetails.tsx
Labels: 🐞 bug

#400 bug: fix usage of subscription id and externalId
  src/components/customers/subscriptions/CustomerSubscriptionsList.tsx
  src/components/customers/subscriptions/SubscriptionItem.tsx
Labels: 🐞 bug

#407 misc(docker): Add ARM64 DockerFile
  Dockerfile.arm64
Labels: 🌈 improvement

#427 Update codegen with the latest version
  src/generated/graphql.tsx
Labels: 🥷 chore

#430 chore: workflows to be run on pull_request
  .github/workflows/linter.yml
  .github/workflows/tests.yml
  .github/workflows/translation-check.yml
  .github/workflows/typescript.yml
Labels: 🥷 chore

#432 fix: 🫡 rename LAGO_SIGNUP_DISABLED const
  .env.sh
  .storybook/main.js
  globals.d.ts
  jest.config.js
  src/core/apolloClient/reactiveVars/envGlobalVar.ts
  webpack.common.js
Labels: 🐞 bug

#416 chore: 🙈 Test bm creation + plan creation
  cypress/e2e/t2-create-customer.cy.ts
  cypress/e2e/t3-create-bm.cy.ts
  cypress/e2e/t4-create-plan.cy.ts
  cypress/e2e/t5-edit-plan.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/support/reusableConstants.ts
  src/components/GenericPlaceholder.tsx
  src/components/billableMetrics/BillableMetricForm.tsx
  src/components/customers/AddCustomerDialog.tsx
  src/components/customers/CustomerItem.tsx
  src/components/customers/subscriptions/AddPlanToCustomerDialog.tsx
  src/components/customers/subscriptions/CustomerSubscriptionsList.tsx
  src/components/designSystem/ButtonLink.tsx
  src/components/designSystem/NavigationTab.tsx
  src/components/form/ComboBox/ComboBoxItem.tsx
  src/components/plans/AddChargeDialog.tsx
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/PlanForm.tsx
  src/components/plans/PlanItem.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreatePlan.tsx
  src/pages/CustomersList.tsx
  src/pages/PlansList.tsx
Labels: 🥷 chore

#428 chore: get last translations version
  ditto/base.json
Labels: 🥷 chore

#415 Members page
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/GenericPlaceholder.tsx
  src/components/settings/members/CreateInviteDialog.tsx
  src/components/settings/members/InviteItem.tsx
  src/components/settings/members/MembershipItem.tsx
  src/components/settings/members/RevokeInviteDialog.tsx
  src/components/settings/members/RevokeMembershipDialog.tsx
  src/core/apolloClient/cache.ts
  src/core/apolloClient/graphqlResolvers.tsx
  src/core/router/index.tsx
  src/generated/graphql.tsx
  src/layouts/Settings.tsx
  src/pages/Invitation.tsx
  src/pages/settings/Members.tsx
  src/styles/auth.tsx
Labels: 🛠 feature

#436 fix(webpack): force process env variable to return a boolean
  webpack.common.js
Labels: 🙀 Critical bug

#434 misc(docker): Build ARM64 Image with CI
  .github/workflows/release.yml
Labels: 🌈 improvement

#437 misc(gh): fix arm64 auto build
  .github/workflows/manual-release.yml
  .github/workflows/release.yml
  Dockerfile.arm64
Labels: 🌈 improvement

#447 fix(LAGO_DISABLE_SIGNUP): env var should be interpreted as a string
  globals.d.ts
  jest.config.js
  src/core/apolloClient/reactiveVars/envGlobalVar.ts
  webpack.common.js
Labels: 🐞 bug

#448 feat: 🥳 Unify currency display in input
  cypress/e2e/t4-create-plan.cy.ts
  cypress/e2e/t5-edit-plan.cy.ts
  ditto/base.json
  src/components/addOns/AddOnItem.tsx
  src/components/coupons/CouponForm.tsx
  src/components/coupons/CouponItem.tsx
  src/components/customers/AddAddOnToCustomerDialog.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/customers/CustomerAddOns.tsx
  src/components/customers/CustomerCoupons.tsx
  src/components/customers/EditCustomerVatRateDialog.tsx
  src/components/customers/usage/UsageItem.tsx
  src/components/form/ComboBox/ComboBoxInput.tsx
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/PackageCharge.tsx
  src/components/plans/PlanForm.tsx
  src/components/plans/VolumeChargeTable.tsx
  src/components/settings/EditOrganizationVatRateDialog.tsx
  src/components/wallets/AddWalletToCustomerDialog.tsx
  src/components/wallets/TopupWalletDialog.tsx
  src/components/wallets/WalletAccordion.tsx
  src/components/wallets/WalletTransactionList.tsx
  src/core/__tests__/intlFormatNumber.test.ts
  src/core/intlFormatNumber.ts
  src/pages/__devOnly/DesignSystem.tsx
  src/styles/muiTheme.ts
Labels: 🥷 chore, 🎨 UI

#453 feat: ✅ add Checkbox component
  src/components/form/Checkbox/Checkbox.tsx
  src/components/form/Checkbox/CheckboxField.tsx
  src/components/form/Checkbox/index.ts
  src/components/form/index.ts
  src/pages/__devOnly/DesignSystem.tsx
  src/stories/Checkbox.stories.tsx
Labels: 🎨 UI

#458 fix(invite): check for email error in details
  src/components/settings/members/CreateInviteDialog.tsx
Labels: 🐞 bug

#457 feat: 🧮 percent coupon
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/coupons/CouponCaption.tsx
  src/components/coupons/CouponCodeSnippet.tsx
  src/components/coupons/CouponForm.tsx
  src/components/coupons/CouponItem.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/customers/CustomerCoupons.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditCoupon.ts
  src/pages/CouponsList.tsx
Labels: 🛠 feature
