Repository getlago/lago-front, pull requests merged in 2022-08, with the labels that each got.

#292 Turn buttons into button links when use for navigation
  package.json
  src/components/addOns/AddOnItem.tsx
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/coupons/CouponItem.tsx
  src/components/designSystem/Button.tsx
  src/components/designSystem/ButtonLink.tsx
  src/components/designSystem/Tabs/NavigationTab.tsx
  src/components/plans/PlanItem.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/AddOnsList.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CouponsList.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreatePlan.tsx
  src/pages/CustomerDetails.tsx
  src/pages/PlansList.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/auth/ForgotPassword.tsx
  src/pages/settings/StripeIntegration.tsx
  yarn.lock
Labels: 🥷 chore, 🌈 improvement

#298 feat: 🗃 DS - Drawer component
  src/components/designSystem/Drawer.tsx
  src/components/designSystem/index.ts
  src/layouts/SideNavLayout.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🎨 UI

#305 fix: 😬 Coupon date should be on one line
  src/components/coupons/CouponItem.tsx
  src/pages/CouponsList.tsx
Labels: 🐞 bug

#314 fix: 🎹 Code snippet billable metric
  src/components/billableMetrics/BillableMetricCodeSnippet.tsx
Labels: 🛠 feature

#316 deps: 🚮 remove storybook
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/stories/Alert.stories.tsx
  src/stories/Introduction.stories.mdx
  src/stories/assets/maneki.png
  yarn.lock
Labels: 🔗 dependencies

#318 deps: 🗄️ add release-it package
  .release-it.js
  CHANGELOG.md
  package.json
  yarn.lock
Labels: 🥷 chore, 🔗 dependencies

#320 fix: 🐹 Charge accordion display
  src/components/form/Radio/Radio.tsx
  src/components/plans/ChargeAccordion.tsx
Labels: 🐞 bug

#319 bug: fix display for customer without name
  ditto/base.json
  src/components/customers/CustomerItem.tsx
  src/components/customers/CustomerMainInfos.tsx
  src/components/designSystem/Avatar.tsx
  src/pages/CustomerDetails.tsx
Labels: 🐞 bug

#322 bug: 🖇️ fix changelog generation
  .auto-changelog
  .changelog/regular.hbs
  .release-it.js
  CHANGELOG.md
  package.json
  yarn.lock
Labels: 🐞 bug

#323 chore: Add linter rule eqeqeq and fix errors
  .eslintrc
  src/components/form/TextInput/TextInput.tsx
  src/components/plans/PlanForm.tsx
Labels: 🥷 chore

#324 chore: Add linter rule no-else-return
  .eslintrc
  src/components/customers/CustomerInvoicesList.tsx
Labels: 🥷 chore

#336 fix: ✂️ prevent focus ring cut in plan form
  src/components/plans/ChargeAccordion.tsx
Labels: 🐞 bug

#338 breaking: use window env
  src/core/router/index.tsx
  src/hooks/core/useInternationalization.ts
  src/index.js
  src/layouts/SideNavLayout.tsx
Labels: 🐞 bug, 💻 dev env

#339 chore: remove environment variable if used once
  src/core/router/index.tsx
  src/hooks/core/useInternationalization.ts
  src/layouts/SideNavLayout.tsx
Labels: 🥷 chore

#340 chore: 🦷 EnvGlobalVar expose env variables
  .env.sh
  .env.template
  src/components/addOns/AddOnCodeSnippet.tsx
  src/components/billableMetrics/BillableMetricCodeSnippet.tsx
  src/components/coupons/CouponCodeSnippet.tsx
  src/components/plans/PlanCodeSnippet.tsx
  src/core/apolloClient/init.ts
  src/core/apolloClient/reactiveVars/envGlobalVar.ts
  src/core/apolloClient/reactiveVars/index.ts
  src/core/router/index.tsx
  src/hooks/core/useInternationalization.ts
  src/index.js
  src/layouts/SideNavLayout.tsx
  src/pages/auth/Login.tsx
  webpack.common.js
  yarn.lock
Labels: 🥷 chore

#341 chore: 🗺 add test for useListKeyNavigation hook
  src/hooks/ui/__tests__/useListKeyNavigation.test.tsx
  src/hooks/ui/useListKeyNavigation.tsx
Labels: 🥷 chore

#342 chore: 🪐 test useInternationalization internal methods
  src/hooks/core/__tests__/useInternationalization.test.ts
  src/hooks/core/useInternationalization.ts
Labels: 🥷 chore

#343 feat: 🪲 Debug dialog
  .github/ISSUE_TEMPLATE/bug.md
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/App.tsx
  src/components/DebugInfoDialog.tsx
  src/hooks/ui/__tests__/useShortcuts.test.tsx
  src/hooks/ui/useShortcuts.tsx
Labels: 🛠 feature

#355 Ci codegen
  .github/workflows/codegen.yml
Labels: ready

#358 test: add test for translate method
  src/hooks/core/__tests__/useInternationalization.test.tsx
Labels: 🧪 testing

#337 [Chore]: Cypress setup + first tests
  .env.template
  .github/workflows/codegen.yml
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/cypress.config.js
  cypress/e2e/auth/t0-signup.cy.ts
  cypress/e2e/auth/t1-login.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  docker-compose.ci.yml
  package.json
  src/components/designSystem/Alert.tsx
  src/components/designSystem/Avatar.tsx
  src/components/designSystem/Button.tsx
  src/components/designSystem/Icon/Icon.tsx
  src/components/designSystem/Status.tsx
  src/components/designSystem/Toasts/Toast.tsx
  src/components/designSystem/Typography.tsx
  src/components/form/TextInput/TextInput.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/SignUp.tsx
  tsconfig.json
  yarn.lock
Labels: 🥷 chore

#364 fix: 🆑 Prevent double focus on button link
  src/components/designSystem/ButtonLink.tsx
Labels: 🐞 bug, 🎨 UI

#362 Update charge percent alert display logic + display currency symbol
  src/components/plans/ChargePercentage.tsx
Labels: 🥷 chore

#377 bug: 💸 fix amount display in disclaimer
  src/components/plans/VolumeChargeTable.tsx
Labels: 🐞 bug

#302 feat: prepaid credit
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/designSystem/Icon/mapping.tsx
  src/components/designSystem/Typography.tsx
  src/components/form/DatePicker/DatePicker.tsx
  src/components/wallets/AddWalletToCustomerDialog.tsx
  src/components/wallets/CustomerWalletList.tsx
  src/components/wallets/TerminateCustomerWalletDialog.tsx
  src/components/wallets/TopupWalletDialog.tsx
  src/components/wallets/UpdateCustomerWalletDialog.tsx
  src/components/wallets/WalletAccordion.tsx
  src/components/wallets/WalletTransactionList.tsx
  src/core/apolloClient/cache.ts
  src/generated/graphql.tsx
  src/pages/CustomerDetails.tsx
  src/public/icons/sync.svg
  src/public/icons/wallet.svg
  src/styles/customer.tsx
Labels: 🛠 feature

#375 fix: 😬 Make sure there is not more than 3 charges
  src/components/customers/usage/UsageItem.tsx
Labels: 🎨 UI
