Repository getlago/lago-front, pull requests merged in 2022-07, with the labels that each got.

#216 Remove unused images
  src/public/images/exploding-head.png
  src/public/images/party.png
  src/public/images/spider-web.png
Labels: 🥷 chore

#222 chore: refactor combobox to send either value or null
  src/components/customers/AddCustomerDialog.tsx
  src/components/form/ComboBox/ComboBoxField.tsx
  src/components/settings/EditOrganizationInformationsDialog.tsx
  src/hooks/useCreateEditCustomer.ts
Labels: 🥷 chore

#223 feat: 🦷 Allow mumtiple charges with same BM
  src/components/plans/AddChargeDialog.tsx
  src/components/plans/PlanForm.tsx
Labels: 🌈 improvement

#225 Uniform formik usage 🥋
  src/components/addOns/AddOnForm.tsx
  src/components/billableMetrics/BillableMetricForm.tsx
  src/components/coupons/CouponForm.tsx
  src/components/customers/AddAddOnToCustomerDialog.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/customers/AddCustomerDialog.tsx
  src/components/plans/PlanForm.tsx
  src/pages/auth/Login.tsx
Labels: 🥷 chore

#232 fix: 🛀 Remove double scrollbar on Combobox
  src/components/form/ComboBox/ComboBoxVirtualizedList.tsx
Labels: 🐞 bug

#233 fix : ⌨️ Text input debounce create glitches
  src/components/form/ButtonSelector/ButtonSelectorField.tsx
  src/components/form/ComboBox/ComboBoxField.tsx
  src/components/form/ComboBox/ComboBoxInput.tsx
  src/components/form/Radio/RadioField.tsx
  src/components/form/Switch/SwitchField.tsx
  src/components/form/TextInput/TextInput.tsx
  src/components/form/TextInput/TextInputField.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/pages/auth/Login.tsx
Labels: 🐞 bug

#224 feat: 🪣 Enable add charge if subscription
  src/components/plans/PlanForm.tsx
Labels: 🌈 improvement

#235 fix: 🎛 Switch can't be disabled
  src/components/form/Switch/Switch.tsx
Labels: 🐞 bug

#230 feat: 🏷 display app version in side nav
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/generated/graphql.tsx
  src/layouts/SideNavLayout.tsx
Labels: 🛠 feature

#240 chore: 🚨 Fix risky dependencies
  package.json
  yarn.lock
Labels: 🥷 chore, 🔗 dependencies

#243 Set webSocketURL for dev env
  webpack.dev.js
Labels: 🥷 chore

#248 chore: 💅 init storybook
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/stories/Introduction.stories.mdx
  src/stories/assets/maneki.png
  yarn.lock
Labels: 🥷 chore

#251 chore: 💅 Add story for the Alert component
  src/stories/Alert.stories.tsx
Labels: 🥷 chore

#256 refactor: 🗑 Hide Charge trash icon if not clickable
  src/components/plans/ChargeAccordion.tsx
Labels: 🌈 improvement

#263 improvement: 📍allow DatePicker to receive it's placement as props
  src/components/form/DatePicker/DatePicker.tsx
Labels: 🌈 improvement

#264 fix: 🔥 ButtonsLink + NavigationLink
  src/components/designSystem/Button.tsx
  src/components/designSystem/ButtonLink.tsx
  src/components/designSystem/Popper.tsx
  src/components/designSystem/Tabs/NavigationTab.tsx
  src/components/designSystem/Tabs/index.ts
  src/components/designSystem/index.ts
  src/components/plans/ChargeAccordion.tsx
  src/core/router/index.tsx
  src/layouts/Developpers.tsx
  src/layouts/Settings.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/settings/StripeIntegration.tsx
Labels: 🐞 bug, 🥷 chore, 🎨 UI

#270 chore: 🐹 Differentiate APP_ENV staging and qa
  globals.d.ts
  jest.config.js
  src/core/router/index.tsx
  src/hooks/core/useInternationalization.ts
  src/layouts/SideNavLayout.tsx
  webpack.common.js
Labels: 🐞 bug, 🥷 chore

#272 fix: 🙄 hidden focus on sidenav buttons
  src/components/designSystem/Tabs/NavigationTab.tsx
Labels: 🐞 bug

#274 fix: 🍎 Display current usage withat VAT
  src/components/customers/CustomerUsage.tsx
  src/generated/graphql.tsx
Labels: 🐞 bug

#288 feat: 📅 Update date format
  src/components/addOns/AddOnItem.tsx
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/coupons/CouponItem.tsx
  src/components/customers/CustomerAddOns.tsx
  src/components/customers/CustomerInvoicesList.tsx
  src/components/customers/CustomerItem.tsx
  src/components/customers/CustomerSubscriptionsList.tsx
  src/components/customers/CustomerUsage.tsx
  src/components/plans/PlanItem.tsx
  src/pages/developpers/Debugger.tsx
Labels: 🌈 improvement

#290 chore: 😬 Add addons typepolicy
  src/core/apolloClient/cache.ts
Labels: 🥷 chore

#289 chore: 🔗 List items are links
  src/components/ConditionalWrapper.tsx
  src/components/addOns/AddOnItem.tsx
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/coupons/CouponItem.tsx
  src/components/customers/CustomerItem.tsx
  src/components/designSystem/ButtonLink.tsx
  src/components/plans/PlanItem.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/styles/designSystem/List.tsx
Labels: 🥷 chore

#291 feat: Display customer's Wallet list
  ditto/base.json
  src/components/designSystem/Icon/mapping.tsx
  src/components/designSystem/Typography.tsx
  src/components/wallets/AddWalletToCustomerDialog.tsx
  src/components/wallets/CustomerWalletList.tsx
  src/components/wallets/WalletAccordion.tsx
  src/components/wallets/WalletTransactionList.tsx
  src/core/apolloClient/cache.ts
  src/generated/graphql.tsx
  src/pages/CustomerDetails.tsx
  src/public/icons/sync.svg
Labels: 🛠 feature

#295 bug: update disabled days color in date picker
  src/components/form/DatePicker/DatePicker.tsx
Labels: 🐞 bug
