Repository getlago/lago-front, pull requests merged in 2022-06, with the labels that each got.

#144 fix: ✨ Add bottom space in event list
  src/pages/developpers/Debugger.tsx
Labels: 🎨 UI

#162 feat: 🤑 Add IDR currency support
  src/generated/graphql.tsx
Labels: 🌈 improvement

#185 feat: 👀 Use 100 unit for percentage charge calculation
  ditto/base.json
  src/components/plans/ChargePercentage.tsx
Labels: 🌈 improvement

#188 feat: 🎛 Switch component update
  src/components/form/Switch/Switch.tsx
  src/components/plans/PlanForm.tsx
Labels: 🌈 improvement, 🎨 UI

#184 feat: 📆 Add weekly billing
  ditto/base.json
  ditto/config.yml
  src/components/plans/PlanForm.tsx
Labels: 🌈 improvement

#195 chore: 🖍 Type Typography colors
  src/components/designSystem/Typography.tsx
  src/components/form/ButtonSelector/ButtonSelector.tsx
  src/components/form/Radio/Radio.tsx
  src/components/form/TextInput/TextInput.tsx
  src/styles/muiTheme.ts
Labels: 🥷 chore

#205 chore: Fix translation
  ditto/base.json
Labels: 🥷 chore
