Repository getlago/lago-front, pull requests merged in 2022-11, with the labels that each got.

#545 [Feat] Allow user to switch organizations
  ditto/base.json
  src/core/apolloClient/reactiveVars/currentUserInfosVar.ts
  src/layouts/SideNavLayout.tsx
Labels: 🌈 improvement

#551 chore(ditto): get last translation version
  ditto/base.json
Labels: 🥷 chore

#550 chore(typo): Fix developer typo, route and folders name
  src/components/developers/DeleteWebhookDialog.tsx
  src/components/developers/EditWebhookDialog.tsx
  src/core/router/index.tsx
  src/hooks/core/__tests__/useLocationHistory.test.ts
  src/layouts/Developers.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/developers/ApiKeys.tsx
  src/pages/developers/Debugger.tsx
  src/pages/developers/Webhook.tsx
Labels: 🥷 chore

#552 chore(column width): adapt customer list column size
  src/components/customers/CustomerItem.tsx
  src/pages/CustomersList.tsx
Labels: 🥷 chore

#568 feat: 🪢 Add credit note list in invoice details
  ditto/base.json
  src/components/customers/creditNotes/VoidCreditNoteDialog.tsx
  src/core/apolloClient/cache.ts
  src/generated/graphql.tsx
  src/pages/InvoiceCreditNoteList.tsx
Labels: 🛠 feature

#573 chore: create one component to handle credit notes list
  ditto/base.json
  src/components/customers/CustomerCreditNotesList.tsx
  src/components/customers/creditNotes/CreditNotesList.tsx
  src/generated/graphql.tsx
  src/pages/InvoiceCreditNoteList.tsx
Labels: 🥷 chore

#576 feat 🎀 Add credit note details page
  ditto/base.json
  src/components/customers/CustomerCreditNotesList.tsx
  src/core/apolloClient/cache.ts
  src/core/router/index.tsx
  src/generated/graphql.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerDetails.tsx
  src/pages/InvoiceCreditNoteDetails.tsx
Labels: 🛠 feature

#575 feat: 🏷 Allow to apply multiple coupons on customer
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/coupons/CouponCaption.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/customers/CustomerCoupons.tsx
  src/generated/graphql.tsx
  src/pages/CustomerDetails.tsx
Labels: 🛠 feature

#588 feat: credit note total to display both credit and refund amounts
  ditto/base.json
  src/generated/graphql.tsx
  src/pages/CreditNoteDetails.tsx
Labels: 🛠 feature

#592 chore: 📏 change the genericPlaceholder default margin-top
  src/components/GenericPlaceholder.tsx
Labels: 🥷 chore

#593 bug: fix vat rate not being udpated in LS and Dynamic vard
  src/components/settings/EditOrganizationVatRateDialog.tsx
  src/core/apolloClient/reactiveVars/currentUserInfosVar.ts
  src/generated/graphql.tsx
Labels: 🐞 bug

#595 bug: increase fetched BMs limit
  src/components/plans/AddChargeDialog.tsx
Labels: 🐞 bug
