Repository getlago/lago-front, pull requests merged in 2022-10, with the labels that each got.

#471 feat(combobox): Display group in startAdorment
  src/components/form/ComboBox/ComboBox.tsx
  src/components/form/ComboBox/ComboBoxInput.tsx
  src/components/form/ComboBox/types.ts
  src/components/form/TextInput/TextInput.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/stories/Combobox.stories.tsx
Labels: 🌈 improvement

#475 fix(translation): use generic wording for Accordion's Tooltip
  ditto/base.json
Labels: 🐞 bug

#479 Fix vulnerabilities
  package.json
  yarn.lock
Labels: 🥷 chore

#480 chore: 🫢 Clean editPlan fragment
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/PackageCharge.tsx
  src/generated/graphql.tsx
  src/hooks/plans/usePlanForm.tsx
  src/pages/CreatePlan.tsx
Labels: 🥷 chore

#485 chore: 🧪 Test useGraduatedChargeForm
  src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx
  src/hooks/plans/useGraduatedChargeForm.ts
Labels: 🥷 chore

#506 feat(charge): group all charge data in a properties object
  cypress/e2e/t4-create-plan.cy.ts
  cypress/e2e/t6-edit-plan.cy.ts
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/PackageCharge.tsx
  src/components/plans/VolumeChargeTable.tsx
  src/core/serializers/serializePlanInput.ts
  src/formValidationSchemas/chargeSchema.ts
  src/generated/graphql.tsx
  src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx
  src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx
  src/hooks/plans/useGraduatedChargeForm.ts
  src/hooks/plans/useVolumeChargeForm.ts
  src/pages/CreatePlan.tsx
Labels: 🌈 improvement

#510 fix(customer) ✍️ Drawer title should only be displayed if data is pre…
  src/components/customers/AddCustomerDrawer.tsx
Labels: 🐞 bug

#514 bug(plan) overriding a plan should keep it's subscription date
  src/components/customers/subscriptions/AddSubscriptionDrawer.tsx
Labels: 🐞 bug

#521 chrore(graph): get last graph version
  src/generated/graphql.tsx
Labels: 🥷 chore
