Repository getlago/lago-front, pull requests merged in 2023-01, with the labels that each got.

#654 chore: ⛑ Reorganize routes
  src/core/router/AuthRoutes.tsx
  src/core/router/CustomerRoutes.tsx
  src/core/router/DevelopperRoutes.tsx
  src/core/router/ObjectsRoutes.tsx
  src/core/router/SettingRoutes.tsx
  src/core/router/index.tsx
  src/core/router/types.ts
Labels: 🥷 chore

#671 bug: allow to hide label on Status
  src/components/customers/InvoicesList.tsx
  src/components/designSystem/Status.tsx
Labels: 🐞 bug

#672 feat: hide Coupon / Prepaid Credit in draft invoice totals and display alert info
  ditto/base.json
  src/components/invoices/InvoiceDetailsTableFooter.tsx
Labels: 🛠 feature

#676 bug: fix credit note tab display for draft invoice
  src/layouts/CustomerInvoiceDetails.tsx
Labels: 🐞 bug

#677 chore: update trads
  ditto/base.json
Labels: 🥷 chore

#687 chore: 🏂 Skip tests in Draft PR
  .github/workflows/tests.yml
Labels: 🥷 chore

#692 bug: fix plan percentage charge serialization
  src/core/serializers/serializePlanInput.ts
Labels: 🐞 bug

#693 feat: 🦷 Fix post massive QA
  src/components/coupons/CouponCodeSnippet.tsx
  src/components/creditNote/CreditNoteFormCalculation.tsx
  src/components/form/DatePicker/DatePicker.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/InvoiceOverview.tsx
Labels: 🐞 bug

#697 bug: fix tab display logic in invoice overview
  src/layouts/CustomerInvoiceDetails.tsx
Labels: 🐞 bug

#698 chore: fix typos in translations
  ditto/base.json
Labels: 🥷 chore

#699 chore: fix react-router-dom index route type definition
  src/components/RouteWrapper.tsx
Labels: 🥷 chore

#707 feat: 🤐 Display resend recollection button
  src/components/invoices/InvoiceListItem.tsx
  src/pages/InvoicesList.tsx
Labels: 🌈 improvement

#706 bug: fix number serialization
  src/core/__tests__/serializeAmount.test.ts
  src/core/serializers/serializeAmount.ts
Labels: 🐞 bug

#705 chore: update graph with bigint
  src/generated/graphql.tsx
Labels: 🌈 improvement

#710 fix: increase BM fetch limit in add dialog
  src/components/plans/AddChargeDialog.tsx
Labels: 🐞 bug

#716 chore: get last translations
  ditto/base.json
Labels: 🥷 chore

#728 chore: copy update
  ditto/base.json
Labels: 🥷 chore

#712 [FEAT]: Coupon set with a frequency "forever"
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/coupons/CouponCaption.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/generated/graphql.tsx
  src/pages/CreateCoupon.tsx
Labels: 🛠 feature

#735 chore: fix some svg wrong syntax
  src/public/icons/filter.svg
  src/public/icons/pulse.svg
  src/public/icons/wallet.svg
Labels: 🥷 chore

#736 chore: make sure we deduplicate packages after install and update
  package.json
  renovate.json
Labels: 🥷 chore

#713 [FEAT]: Delete BM with subscription
  ditto/base.json
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/billableMetrics/DeleteBillableMetricDialog.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditBillableMetric.ts
  src/pages/CreateBillableMetric.tsx
Labels: 🛠 feature

#741 chore: update chip styles
  src/components/designSystem/Chip.tsx
Labels: 🥷 chore

#740 chore: 🫣 Create session for E2E tests
  cypress/e2e/auth/t1-login.cy.ts
  cypress/e2e/t2-create-customer.cy.ts
  cypress/e2e/t3-create-bm.cy.ts
  cypress/e2e/t4-create-plan.cy.ts
  cypress/e2e/t6-edit-plan.cy.ts
  cypress/support/e2e.ts
Labels: 🥷 chore

#742 feat: 🗑 Delete charge used in subscription
  cypress/e2e/t6-edit-plan.cy.ts
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/plans/ChargeAccordion.tsx
  src/pages/CreatePlan.tsx
Labels: 🛠 feature

#748 chore(deps): bump loader-utils from 1.4.0 to 1.4.2
  yarn.lock
Labels: 🥷 chore

#749 bug: set loading to true by default
  src/hooks/useDebouncedSearch.ts
Labels: 🐞 bug

#758 bug: fix amount cents type
  src/components/customers/CustomerCreditNotesList.tsx
  src/hooks/useCreateCreditNote.ts
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/InvoiceCreditNoteList.tsx
Labels: 🐞 bug

#759 Fix checkbox style
  src/generated/graphql.tsx
  src/styles/muiTheme.ts
Labels: 🐞 bug

#743 🗑 Delete Plan with subscription
  ditto/base.json
  src/components/plans/DeletePlanDialog.tsx
  src/components/plans/PlanItem.tsx
  src/generated/graphql.tsx
  src/pages/CreatePlan.tsx
Labels: 🛠 feature

#760 chore: get last translation update
  ditto/base.json
Labels: 🥷 chore

#762 chore: unify terminate plan copy
  ditto/base.json
  src/components/plans/DeletePlanDialog.tsx
Labels: 🥷 chore

#761 bug: fix invoice loading state behaviour
  src/components/customers/CustomerInvoicesTab.tsx
Labels: 🐞 bug
