Repository getlago/lago-front, pull requests merged in 2023-10, with the labels that each got.

#1250 bug(webhook) prevent long url to overflow
  src/pages/developers/Webhooks.tsx
Labels: 🐞 bug

#1247 feat: customise invoice display name
  cypress/e2e/10-resources/t40-create-plan.cy.ts
  cypress/e2e/10-resources/t60-coupons-create-edit-apply.cy.ts
  cypress/e2e/t30-create-one-off-invoice.cy.ts
  src/components/customers/CustomerCoupons.tsx
  src/components/customers/usage/CustomerUsageDetailDrawer.tsx
  src/components/customers/usage/UsageItem.tsx
  src/components/invoices/InvoiceCreditNotesTable.tsx
  src/components/invoices/InvoiceDetailsTable.tsx
  src/components/invoices/InvoiceDetailsTableFeeItem.tsx
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargesSection.tsx
  src/components/plans/__tests__/ChargeAccordion.test.tsx
  src/core/formats/formatInvoiceItemsMap.ts
  src/core/serializers/serializePlanInput.ts
  src/formValidation/__tests__/chargeSchemaVolume.test.ts
  src/generated/graphql.tsx
  src/hooks/plans/usePlanForm.tsx
  src/hooks/useCreateCreditNote.ts
  src/pages/CreateCreditNote.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreatePlan.tsx
  src/pages/CreditNoteDetails.tsx
Labels: 🛠 feature

#1253 bug(cache) fine tune customer cache policy
  src/core/apolloClient/cache.ts
Labels: 🐞 bug

#1254 feat(customer) add field for external salesforce id
  ditto/base.json
  src/components/customers/AddCustomerDrawer.tsx
  src/components/customers/CustomerMainInfos.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditCustomer.ts
Labels: 🛠 feature

#1255 feat(charge) display code in the charge accordion summary
  src/components/plans/ChargeAccordion.tsx
Labels: 🌈 improvement

#1257 bug(ChargeAccordion) fix spacing with the Alert and content
  src/components/plans/ChargeAccordion.tsx
Labels: 🐞 bug

#1258 bug(DatePicker): apply flip modifier if placement is auto
  src/components/form/DatePicker/DatePicker.tsx
Labels: 🐞 bug

#1259 feat: plan override when creating a subscription and subscription details
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/e2e/t10-add-subscription.cy.ts
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  package.json
  src/components/SkeletonDetailsPage.tsx
  src/components/customers/subscriptions/AddSubscriptionDrawer.tsx
  src/components/customers/subscriptions/CustomerSubscriptionsList.tsx
  src/components/customers/subscriptions/EditCustomerSubscriptionDrawer.tsx
  src/components/customers/subscriptions/SubscriptionItem.tsx
  src/components/customers/subscriptions/SubscriptionLine.tsx
  src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx
  src/components/designSystem/Avatar.tsx
  src/components/designSystem/Selector.tsx
  src/components/form/ComboBox/ComboBoxInput.tsx
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/ChargesSection.tsx
  src/components/plans/FixedFeeSection.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/GraduatedPercentageChargeTable.tsx
  src/components/plans/PackageCharge.tsx
  src/components/plans/PlanItem.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/components/plans/VolumeChargeTable.tsx
  src/components/plans/__tests__/ChargeAccordion.test.tsx
  src/components/plans/details/PlanDetailsChargeTableDisplay.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/components/plans/details/PlanDetailsChargesSection.tsx
  src/components/plans/details/PlanDetailsChargesSectionAccordion.tsx
  src/components/plans/details/PlanDetailsFixedFeeAccordion.tsx
  src/components/plans/details/PlanDetailsOverview.tsx
  src/components/subscriptions/SubscriptionDetailsOverview.tsx
  src/components/subscriptions/SubscriptionInformations.tsx
  src/core/apolloClient/reactiveVars/duplicatePlanVar.ts
  src/core/apolloClient/reactiveVars/index.ts
  src/core/apolloClient/reactiveVars/overwritePlanVar.ts
  src/core/constants/form.ts
  src/core/router/ObjectsRoutes.tsx
  src/core/router/index.tsx
  src/core/router/utils.tsx
  src/core/serializers/getPropertyShape.ts
  src/generated/graphql.tsx
  src/hooks/__tests__/fixtures.ts
  src/hooks/customer/useAddSubscription.tsx
  src/hooks/plans/usePlanForm.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/CreatePlan.tsx
  src/pages/CreateSubscription.tsx
  src/pages/CustomerDetails.tsx
  src/pages/PlansList.tsx
  src/pages/SubscriptionDetails.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/public/images/maneki/thinking.svg
  src/styles/designSystem/Card.tsx
  src/styles/detailsPage.tsx
  src/styles/muiTheme.ts
  yarn.lock
Labels: 🛠 feature

#1263 bug(group-properties) no group by default when adding a charge
  src/components/plans/ChargesSection.tsx
Labels: 🐞 bug

#1266 chore(fixture) fix fee attributes
  src/hooks/__tests__/fixtures.ts
Labels: 🥷 chore

#1264 feat(plan) add details page
  cypress/e2e/10-resources/t40-create-plan.cy.ts
  cypress/e2e/10-resources/t50-edit-plan.cy.ts
  cypress/support/reusableConstants.ts
  ditto/base.json
  src/components/SkeletonDetailsPage.tsx
  src/components/plans/DeletePlanDialog.tsx
  src/components/plans/PlanItem.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/components/plans/details/PlanDetailsChargesSection.tsx
  src/components/plans/details/PlanDetailsFixedFeeAccordion.tsx
  src/components/plans/details/PlanSubscriptionList.tsx
  src/components/plans/details/PlanSubscriptionListItem.tsx
  src/components/subscriptions/SubscriptionDetailsOverview.tsx
  src/components/subscriptions/SubscriptionInformations.tsx
  src/core/apolloClient/cache.ts
  src/core/router/ObjectsRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/plans/usePlanForm.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/CreatePlan.tsx
  src/pages/PlanDetails.tsx
  src/pages/PlansList.tsx
  src/pages/SubscriptionDetails.tsx
Labels: 🛠 feature

#1268 bug(nav) plan sub route should allow nav button click
  src/layouts/SideNavLayout.tsx
Labels: 🐞 bug

#1269 bug(subscription) hide parent on upgrade/downgrade
  src/pages/CreateSubscription.tsx
Labels: 🐞 bug

#1260 feat(invoice) allow to void and invoice
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/customerPortal/PortalInvoicesList.tsx
  src/components/customers/CustomerInvoicesList.tsx
  src/components/customers/CustomerInvoicesTab.tsx
  src/components/designSystem/Status.tsx
  src/components/invoices/EditInvoicePaymentStatusDialog.tsx
  src/components/invoices/InvoiceCustomerInfos.tsx
  src/components/invoices/InvoiceListItem.tsx
  src/components/invoices/VoidInvoiceDialog.tsx
  src/generated/graphql.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/CustomerDraftInvoicesList.tsx
  src/pages/InvoiceCreditNoteList.tsx
  src/pages/InvoicesList.tsx
Labels: 🛠 feature

#1271 chore(copy): Get last translations version
  ditto/base.json
Labels: 🥷 chore

#1272 bug(list) fix duplicated items
  src/hooks/useDebouncedSearch.ts
Labels: 🐞 bug

#1275 chore(router) update customer :id name in router
  src/components/customers/CustomerCoupons.tsx
  src/components/customers/CustomerInvoicesTab.tsx
  src/components/customers/CustomerItem.tsx
  src/components/customers/EditCustomerInvoiceGracePeriodDialog.tsx
  src/components/customers/creditNotes/CreditNotesList.tsx
  src/components/customers/subscriptions/CustomerSubscriptionsList.tsx
  src/components/customers/subscriptions/SubscriptionLine.tsx
  src/components/customers/usage/CustomerUsage.tsx
  src/components/invoices/InvoiceCreditNotesTable.tsx
  src/components/invoices/InvoiceCustomerInfos.tsx
  src/components/subscriptions/SubscriptionInformations.tsx
  src/core/router/CustomerRoutes.tsx
  src/core/router/ObjectsRoutes.tsx
  src/hooks/customer/useAddSubscription.tsx
  src/hooks/useCreateCreditNote.ts
  src/hooks/useCreateEditCustomer.ts
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/CreateCreditNote.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreateSubscription.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerDetails.tsx
  src/pages/CustomerDraftInvoicesList.tsx
  src/pages/InvoiceCreditNoteList.tsx
  src/pages/InvoicesList.tsx
  src/pages/SubscriptionDetails.tsx
Labels: 🥷 chore

#1277 bug(plan) fix details display
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
Labels: 🐞 bug

#1276 chore(input) add default border radius
  src/styles/muiTheme.ts
Labels: 🥷 chore

#1279 bug(plan) fix details display
  src/components/plans/details/PlanDetailsChargeTableDisplay.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/components/plans/details/PlanDetailsFixedFeeAccordion.tsx
Labels: 🐞 bug

#1285 bug(billable-metrics): fix pagination
  src/core/apolloClient/cache.ts
  src/generated/graphql.tsx
Labels: 🐞 bug

#1286 misc: add chart-bar icon
  src/components/designSystem/Icon/mapping.tsx
  src/public/icons/chart-bar.svg
Labels: 🥷 chore

#1287 misc: add bigNumberShortenNotationFormater helper
  src/core/formats/__tests__/intlFormatNumber.test.ts
  src/core/formats/intlFormatNumber.ts
Labels: 🥷 chore
