Repository getlago/lago-front, pull requests merged in 2023-09, with the labels that each got.

#1196 chore(node) update version to LTS (v18)
  .github/workflows/codegen.yml
  .github/workflows/cypress.yml
  .github/workflows/linter.yml
  .github/workflows/tests.yml
  .github/workflows/translation-check.yml
  .github/workflows/translation-update.yml
  .github/workflows/typescript.yml
  Dockerfile
  Dockerfile.dev
  package.json
Labels: 🥷 chore, 🔗 dependencies

#1194 chore(graph) get last version
  src/generated/graphql.tsx
Labels: 🥷 chore

#1198 chore(test) add test for useCreateCreditNote hook
  jest.config.js
  src/components/coupons/__tests__/CouponCaption.test.tsx
  src/hooks/__tests__/fixtures.ts
  src/hooks/__tests__/useCreateCreditNote.test.ts
  src/test-utils.tsx
Labels: 🧪 testing

#1200 chore(copy) get last translations
  ditto/base.json
Labels: 🥷 chore

#1201 chore(test) extract and test CreditNoteFormCalculation's calculation method
  src/components/creditNote/CreditNoteFormCalculation.tsx
  src/components/creditNote/__tests__/fixtures.ts
  src/components/creditNote/__tests__/utils.test.ts
  src/components/creditNote/utils.ts
Labels: 🧪 testing

#1205 feat: duplicate plan from another
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/customers/subscriptions/AddSubscriptionDrawer.tsx
  src/components/plans/PlanItem.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/core/apolloClient/reactiveVars/overwritePlanVar.ts
  src/generated/graphql.tsx
  src/hooks/plans/usePlanForm.tsx
  src/pages/CreatePlan.tsx
Labels: 🛠 feature

#1199 feat(billable-metric) add Last aggregation type
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/billableMetrics/BillableMetricCodeSnippet.tsx
  src/components/plans/ChargeAccordion.tsx
  src/generated/graphql.tsx
  src/pages/CreateBillableMetric.tsx
Labels: 🛠 feature

#1209 chore(scripts) fix glob usage
  ditto/base.json
  ditto/de.json
  ditto/fr.json
  ditto/it.json
  ditto/nb.json
  package.json
  scripts/InspectTranslationKeys.js
  scripts/MergeTranslationFiles.js
  yarn.lock
Labels: 🥷 chore

#1206 chore(ci) combine workflows
  .github/workflows/linter.yml
  .github/workflows/translation-check.yml
  .github/workflows/typescript.yml
Labels: 🥷 chore

#1212 chore(sentry) update deprecated BrowserTracing usage
  src/index.js
Labels: 🥷 chore

#1216 chore: improve auto scroll behaviour
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargesSection.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/pages/CreateAddOn.tsx
Labels: 🥷 chore

#1220 chore(test) add test for basic form calculation component
  src/components/creditNote/CreditNoteFormCalculation.tsx
  src/components/creditNote/__tests__/CreditNoteFormCalculation.test.tsx
  src/components/creditNote/__tests__/fixtures.ts
  yarn.lock
Labels: 🧪 testing

#1221 chore(test) add more test on schema validation
  jest.config.js
  src/formValidation/__tests__/feesSchema.test.ts
  src/formValidation/__tests__/metadataSchema.test.ts
  src/formValidation/feesSchema.ts
  src/formValidation/metadataSchema.ts
Labels: 🧪 testing

#1213 feat(invoice) customise subscription fee display name for invoice
  cypress/e2e/10-resources/t50-edit-plan.cy.ts
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/invoices/EditInvoiceDisplayName.tsx
  src/components/invoices/InvoiceDetailsTable.tsx
  src/components/invoices/InvoiceDetailsTableFeeItem.tsx
  src/components/plans/FixedFeeSection.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/core/apolloClient/reactiveVars/overwritePlanVar.ts
  src/generated/graphql.tsx
  src/hooks/plans/usePlanForm.tsx
  src/pages/CreatePlan.tsx
Labels: 🛠 feature

#1223 bug(addon) remove tooltip that does not make sense anymore
  ditto/base.json
  src/components/addOns/AddOnItem.tsx
Labels: 🐞 bug

#1224 feat(credit-note) display invoice display name if present
  src/components/invoices/InvoiceCreditNotesTable.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateCreditNote.ts
  src/pages/CreditNoteDetails.tsx
Labels: 🛠 feature

#1226 chore(nginx) update config to support IPV6
  nginx/nginx.conf
Labels: 🥷 chore

#1227 chore(graph) rename customerCount attribute to customersCount
  src/components/addOns/AddOnItem.tsx
  src/components/coupons/CouponItem.tsx
  src/components/customers/CustomerItem.tsx
  src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx
  src/components/plans/PlanItem.tsx
  src/generated/graphql.tsx
  src/hooks/customer/useAddSubscription.tsx
  src/pages/CustomerDetails.tsx
Labels: 🥷 chore

#1179 feat(subscription): add end date
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/customers/subscriptions/AddSubscriptionDrawer.tsx
  src/components/customers/subscriptions/EditCustomerSubscriptionDrawer.tsx
  src/components/customers/subscriptions/SubscriptionDatesOffsetHelperComponent.tsx
  src/components/customers/subscriptions/SubscriptionItem.tsx
  src/components/customers/subscriptions/SubscriptionLine.tsx
  src/components/customers/subscriptions/__tests__/SubscriptionDatesOffsetHelperComponent.test.tsx
  src/components/form/DatePicker/DatePicker.tsx
  src/components/form/TimePicker/TimePicker.tsx
  src/components/form/TimePicker/TimePickerField.tsx
  src/components/form/TimePicker/index.ts
  src/core/apolloClient/reactiveVars/overwritePlanVar.ts
  src/core/constants/form.ts
  src/core/timezone/__tests__/config.test.ts
  src/generated/graphql.tsx
  src/hooks/customer/useAddSubscription.tsx
  src/hooks/useOrganizationInfos.ts
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🛠 feature

#1231 chore(plan-override) prevent sending parentId to BE
  src/generated/graphql.tsx
  src/hooks/plans/usePlanForm.tsx
Labels: 🥷 chore

#1238 chore(fixture) add missing params
  src/generated/graphql.tsx
  src/hooks/__tests__/fixtures.ts
Labels: 🥷 chore

#1239 chore(copy): Get last translations version
  ditto/base.json
Labels: 🥷 chore

#1241 bug(email) prevent uppercase value on any email field
  src/components/customers/AddCustomerDrawer.tsx
  src/components/form/TextInput/TextInput.tsx
  src/components/form/TextInput/__tests__/FormatValue.test.ts
  src/components/settings/EditOrganizationInformationsDialog.tsx
  src/components/settings/members/CreateInviteDialog.tsx
  src/pages/Invitation.tsx
  src/pages/auth/ForgotPassword.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/SignUp.tsx
Labels: 🐞 bug

#1242 feat: add weighted sum BM code snippet
  src/components/billableMetrics/BillableMetricCodeSnippet.tsx
  src/core/utils/BMGroupUtils.ts
Labels: 🐞 bug, 🛠 feature

#1243 bug(usage) fix duplicate usage drawer data
  src/components/customers/usage/UsageItem.tsx
Labels: 🐞 bug
