Repository getlago/lago-front, pull requests merged in 2023-02, with the labels that each got.

#767 chore: reset addon dialog on click away
  src/components/customers/AddAddOnToCustomerDialog.tsx
Labels: 🥷 chore

#769 bug: 🏷️ fix coupons alert wrongly displayed
  src/generated/graphql.tsx
  src/pages/CreateCoupon.tsx
Labels: 🐞 bug

#770 feat: disable plan and BM edit if subscription existed
  src/generated/graphql.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreatePlan.tsx
Labels: 🛠 feature

#771 feat: udpate edit coupon and addon disabled logic
  src/components/addOns/AddOnItem.tsx
  src/components/coupons/CouponItem.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditAddOn.ts
  src/hooks/useCreateEditCoupon.ts
  src/pages/CreateAddOn.tsx
  src/pages/CreateCoupon.tsx
Labels: 🛠 feature

#782 chore: rename countryCode.json file
  src/components/customers/AddCustomerDrawer.tsx
  src/components/customers/CustomerMainInfos.tsx
  src/components/invoices/InvoiceCustomerInfos.tsx
  src/components/settings/EditOrganizationInformationsDialog.tsx
  src/pages/settings/OrganizationInformations.tsx
  src/public/countryCodes.json
Labels: 🥷 chore

#783 bug: 🐟 fix edition rule for BM in plan form
  src/generated/graphql.tsx
  src/pages/CreatePlan.tsx
Labels: 🐞 bug

#784 chore: 🚢 fix warning peer deps not installed
  package.json
  yarn.lock
Labels: 🥷 chore

#785 bug: 🧢 fix AddOns credit note label
  src/components/invoices/InvoiceCreditNotesTable.tsx
  src/generated/graphql.tsx
  src/pages/CreditNoteDetails.tsx
Labels: 🐞 bug

#787 feat: show warning if a BM already exists in plan
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/plans/AddChargeDialog.tsx
  src/generated/graphql.tsx
  src/pages/CreatePlan.tsx
Labels: 🌈 improvement

#792 bug: fix charge percentage delete messing with attributes value
  src/components/plans/ChargePercentage.tsx
Labels: 🐞 bug

#793 chore: remove unused mutation
  src/components/wallets/CustomerWalletList.tsx
  src/generated/graphql.tsx
Labels: 🥷 chore

#794 chore: fix oso svg rendering
  src/public/images/oso.svg
Labels: 🥷 chore

#796 test: add anti-regression test scenario
  cypress/e2e/t4-create-plan.cy.ts
  src/components/plans/ChargePercentage.tsx
Labels: 🧪 testing

#799 chore: remove useless section in PR template
  PULL_REQUEST_TEMPLATE.md
Labels: 🥷 chore

#797 chore: update cache when coupon is terminated
  src/components/customers/CustomerCoupons.tsx
Labels: 🥷 chore

#795 chore: store organization billing info in a new internal object
  cypress/e2e/auth/t0-signup.cy.ts
  src/components/customers/CustomerSettings.tsx
  src/components/settings/EditOrganizationGracePeriodDialog.tsx
  src/components/settings/EditOrganizationInvoiceTemplateDialog.tsx
  src/components/settings/EditOrganizationVatRateDialog.tsx
  src/generated/graphql.tsx
  src/pages/settings/InvoiceSettings.tsx
Labels: 🥷 chore

#810 chore: update codegen with last api changes
  src/generated/graphql.tsx
Labels: 🥷 chore

#814 bug: fix location reload invocation
  src/components/customers/CustomerInvoicesList.tsx
  src/pages/InvoicesList.tsx
  src/pages/developers/Debugger.tsx
Labels: 🐞 bug

#817 chore: 👓 Manually update cache on customer creation
  src/hooks/useCreateEditCustomer.ts
Labels: 🥷 chore

#824 chore: remove release-it package
  .changelog/regular.hbs
  .release-it.js
  CHANGELOG.md
  package.json
  yarn.lock
Labels: 🥷 chore

#830 feat: initially open group dimension accordion on condition
  src/pages/CreateBillableMetric.tsx
Labels: 🌈 improvement

#832 chore: copy update
  ditto/base.json
Labels: 🥷 chore

#831 test: make cy.type blazingly fast
  cypress/support/commands.ts
Labels: 🧪 testing

#839 test: set 0ms timeout in cypress env
  globals.d.ts
  src/hooks/useDebouncedSearch.ts
Labels: 🥷 chore, 🧪 testing

#847 breaking(node): minimal node version is now v16
  .github/workflows/codegen.yml
  .github/workflows/cypress.yml
  .github/workflows/linter.yml
  .github/workflows/stories.yml
  .github/workflows/tests.yml
  .github/workflows/translation-check.yml
  .github/workflows/typescript.yml
  Dockerfile
  Dockerfile.arm64
  Dockerfile.dev
  package.json
Labels: 🥷 chore, 🔗 dependencies

#849 bug: fix scrollbar always shown
  src/components/customers/CustomerInvoicesList.tsx
  src/layouts/SideNavLayout.tsx
Labels: 🐞 bug, 🎨 UI

#850 misc(credit notes): use math round in credit note form calculation
  src/components/creditNote/CreditNoteFormCalculation.tsx
Labels: 🥷 chore

#853 fix: 🦆 Error while adding an add-on
  src/components/customers/AddAddOnToCustomerDialog.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/generated/graphql.tsx
  src/pages/CustomerDetails.tsx
Labels: 🐞 bug

#852 chore: 🍾 Remove MUI from Skeleton
  src/components/designSystem/Skeleton.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/stories/Skeleton.stories.tsx
Labels: 🥷 chore
