Repository getlago/lago-front, pull requests merged in 2023-08, with the labels that each got.

#1124 bug(draft-invoice) fix alert padding top value
  src/pages/InvoiceOverview.tsx
Labels: 🐞 bug

#1125 feat: allow delete 1 more tier
  ditto/base.json
  src/components/plans/GraduatedChargeTable.tsx
  src/core/constants/form.ts
  src/formValidation/chargeSchema.ts
  src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx
  src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx
  src/hooks/plans/useGraduatedChargeForm.ts
  src/hooks/plans/useVolumeChargeForm.ts
Labels: 🛠 feature

#1127 feat(webhook) allow to select webhook signature algo
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/developers/CreateWebhookDialog.tsx
  src/components/form/Radio/Radio.tsx
  src/generated/graphql.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/developers/Webhooks.tsx
Labels: 🛠 feature

#1128 chore(copy) fix keys missmatch
  ditto/base.json
  src/components/plans/ChargesSection.tsx
  src/pages/CreateBillableMetric.tsx
Labels: 🥷 chore

#1132 chore(test) create one-off invoice with taxes
  cypress/e2e/t30-create-one-off-invoice.cy.ts
  src/components/customers/CustomerInvoicesList.tsx
  src/components/invoices/EditInvoiceItemTaxDialog.tsx
  src/components/invoices/InvoiceDetailsTableFooter.tsx
  src/components/invoices/InvoiceListItem.tsx
  src/core/constants/form.ts
  src/pages/CreateInvoice.tsx
  src/pages/CustomerDetails.tsx
Labels: 🥷 chore, 🧪 testing

#1133 chore(copy) fix typo
  ditto/base.json
Labels: 🥷 chore

#1135 bug(subscription) fix CTA wording on cancel
  src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx
Labels: 🐞 bug

#1149 chore: copy update
  ditto/base.json
Labels: 🥷 chore

#1150 feat(charges) Allow to set a default property for grouped charges
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  jest.config.js
  package.json
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargeWrapperSwitch.tsx
  src/components/plans/ChargesSection.tsx
  src/components/plans/ConditionalChargeWrapper.tsx
  src/components/plans/__tests__/ChargeAccordion.test.tsx
  src/core/constants/form.ts
  src/core/serializers/__tests__/serializePlanInput.test.ts
  src/core/serializers/serializePlanInput.ts
  src/formValidation/chargeSchema.ts
  src/pages/CreatePlan.tsx
  src/styles/muiTheme.ts
  src/test-utils.tsx
  yarn.lock
Labels: 🛠 feature

#1154 chore(renovate) change schedule
  renovate.json
Labels: 🥷 chore, 🔗 dependencies

#1158 bug(charge) fix spacing between button and groups
  src/components/plans/ChargeAccordion.tsx
Labels: 🐞 bug

#1161 chore(test) add test for countryDataForCombobox
  package.json
  src/core/formats/__tests__/countryDataForCombobox.test.ts
Labels: 🥷 chore, 🧪 testing

#1162 bug(invoice) fix total calculation when editing invoice item's units with tax
  cypress/e2e/t30-create-one-off-invoice.cy.ts
  src/pages/CreateInvoice.tsx
Labels: 🐞 bug

#1159 feat(percentage-charge) allow to set min and max values
  cypress/e2e/10-resources/t40-create-plan.cy.ts
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/ChargeWrapperSwitch.tsx
  src/core/constants/form.ts
  src/core/serializers/__tests__/serializePlanInput.test.ts
  src/core/serializers/serializePlanInput.ts
  src/formValidation/chargeSchema.ts
  src/generated/graphql.tsx
  src/pages/CreatePlan.tsx
Labels: 🛠 feature

#1164 chore(test) add test for copyToClipboard
  jest.config.js
  src/core/utils/__tests__/copyToClipboard.test.ts
Labels: 🥷 chore, 🧪 testing

#1168 chore: add action to create PR with last copy update
  .github/workflows/translation-update.yml
Labels: 🥷 chore

#1170 chore: fix Translation Update action
  .github/workflows/translation-update.yml
Labels: 🥷 chore

#1171 chore(action) use local script in translation-update action
  .github/workflows/translation-update.yml
Labels: 🥷 chore

#1175 chore: Add test for WarningDialog component
  src/components/WarningDialog.tsx
  src/components/__tests__/WarningDialog.test.tsx
  src/components/designSystem/Dialog.tsx
Labels: 🥷 chore, 🧪 testing

#1178 chore(copy): Get last translations version
  ditto/base.json
Labels: 🥷 chore
