Repository getlago/lago-front, pull requests merged in 2024-06, with the labels that each got.

#1519 feat: invite members with role
  ditto/base.json
  src/components/customers/creditNotes/VoidCreditNoteDialog.tsx
  src/components/designSystem/Button.tsx
  src/components/designSystem/NavigationTab.tsx
  src/components/invoices/CreditNoteListItem.tsx
  src/components/invoices/CreditNotesList.tsx
  src/components/invoices/InvoiceListItem.tsx
  src/components/invoices/InvoicesList.tsx
  src/components/settings/members/CreateInviteDialog.tsx
  src/components/settings/members/EditInviteRoleDialog.tsx
  src/components/settings/members/EditMemberRoleDialog.tsx
  src/components/settings/members/InviteItem.tsx
  src/components/settings/members/MembershipItem.tsx
  src/components/settings/members/RevokeMembershipDialog.tsx
  src/components/settings/members/RolePickerField.tsx
  src/components/wallets/CustomerWalletList.tsx
  src/core/apolloClient/cache.ts
  src/core/constants/externalUrls.ts
  src/core/constants/form.ts
  src/core/router/CustomerRoutes.tsx
  src/core/router/ObjectsRoutes.tsx
  src/generated/graphql.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/CustomersList.tsx
  src/pages/InvoicesPage.tsx
  src/pages/SubscriptionDetails.tsx
  src/pages/settings/InvoiceSettings.tsx
  src/pages/settings/Members.tsx
Labels: 🛠 feature

#1529 misc: handle freemium display on invite role modal
  ditto/base.json
  src/components/form/Radio/Radio.tsx
  src/components/settings/members/RolePickerField.tsx
Labels: 🌈 improvement

#1527 refactor: use builder to write our code snippets
  src/components/CodeSnippet.tsx
  src/core/utils/__tests__/copyToClipboard.test.ts
  src/core/utils/__tests__/snippetBuilder.test.ts
  src/core/utils/copyToClipboard.ts
  src/core/utils/snippetBuilder.ts
Labels: 🌈 improvement

#1533 bug: restore date picker label display
  ditto/base.json
  src/components/form/DatePicker/DatePicker.tsx
Labels: 🐞 bug

#1534 bug: make invoice switcher button use caption text
  src/components/invoices/InvoicesList.tsx
Labels: 🐞 bug

#1536 bug: allow to add Netsuite connection on customer edit
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
Labels: 🐞 bug

#1535 misc: add new navigationTab component
  src/components/designSystem/NavigationTab.tsx
  src/components/designSystem/VerticalMenu.tsx
  src/components/designSystem/index.ts
  src/layouts/CustomerInvoiceDetails.tsx
  src/layouts/Developers.tsx
  src/layouts/Settings.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/CustomerDetails.tsx
  src/pages/InvoicesPage.tsx
  src/pages/PlanDetails.tsx
  src/pages/SubscriptionDetails.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/developers/WebhookLogs.tsx
  src/pages/settings/NetsuiteIntegrationDetails.tsx
Labels: 🌈 improvement

#1537 misc: add default empty state in credit note list page
  ditto/base.json
  src/components/customers/creditNotes/CreditNotesList.tsx
Labels: 🌈 improvement

#1539 misc: enable FF for all non-prod env
  src/index.js
Labels: 🥷 chore

#1540 misc: make sure initial render does not raise a warning
  src/components/designSystem/NavigationTab.tsx
Labels: 🥷 chore

#1541 bug: fix selector skeleton loading render
  src/components/designSystem/Selector.tsx
Labels: 🐞 bug

#1542 bug: default combobox label variant should be body
  src/components/form/ComboBox/ComboBoxItem.tsx
  src/components/form/Radio/Radio.tsx
Labels: 🐞 bug

#1543 misc: fix back navigation on integration deletion
  src/components/settings/integrations/NetsuiteIntegrationSettings.tsx
  src/generated/graphql.tsx
  src/pages/settings/AdyenIntegrationDetails.tsx
  src/pages/settings/GocardlessIntegrationDetails.tsx
  src/pages/settings/NetsuiteIntegrationDetails.tsx
  src/pages/settings/StripeIntegrationDetails.tsx
Labels: 🥷 chore

#1545 bug: render nav children even if there is only one tab
  src/components/designSystem/NavigationTab.tsx
  src/layouts/CustomerInvoiceDetails.tsx
Labels: 🐞 bug

#1547 chore: rename methods and attributes
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/generated/graphql.tsx
Labels: 🥷 chore

#1548 misc: silent auth and permissions related errors by default
  src/core/apolloClient/init.ts
Labels: 🥷 chore

#1546 feat: update status component
  ditto/base.json
  src/components/coupons/CouponItem.tsx
  src/components/customerPortal/PortalInvoiceListItem.tsx
  src/components/customers/subscriptions/CustomerSubscriptionsList.tsx
  src/components/customers/subscriptions/SubscriptionLine.tsx
  src/components/designSystem/Status.tsx
  src/components/designSystem/Typography.tsx
  src/components/invoices/InvoiceCustomerInfos.tsx
  src/components/invoices/InvoiceListItem.tsx
  src/components/subscriptions/SubscriptionInformations.tsx
  src/components/wallets/WalletAccordion.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/CouponsList.tsx
  src/pages/CreateCreditNote.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🌈 improvement

#1550 misc: customer netsuiteCustomer is not an array of providers
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditCustomer.ts
Labels: 🥷 chore

#1551 misc: update selected tab when url changes
  src/components/designSystem/NavigationTab.tsx
Labels: 🥷 chore

#1553 misc: Anrok connection needs to have a connectionID mapped
  src/components/settings/integrations/AddAnrokDialog.tsx
  src/generated/graphql.tsx
Labels: 🥷 chore

#1555 fix: assign plan submit button
  src/hooks/plans/usePlanForm.tsx
Labels: 🐞 bug

#1562 feat: new display table component
  src/components/designSystem/Table/TableDisplay.tsx
  src/components/designSystem/Table/index.ts
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🎨 UI

#1563 chore: improve integration deletion object serialization
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
Labels: 🥷 chore

#1564 misc: prepare customer <> Anrok link
  ditto/base.json
  src/components/customers/CustomerMainInfos.tsx
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/core/constants/externalUrls.ts
  src/core/constants/form.ts
  src/generated/graphql.tsx
  src/hooks/useCreateEditCustomer.ts
Labels: 🛠 feature

#1565 fix: display show more on customer details
  src/components/customers/CustomerMainInfos.tsx
Labels: 🌈 improvement

#1566 misc: order alphabetically combobox group values
  src/components/form/ComboBox/ComboboxList.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxList.tsx
Labels: 🥷 chore

#1567 bug: prevent padding in radio focus ring
  src/components/form/Radio/Radio.tsx
Labels: 🐞 bug

#1568 Handle missing TZ
  ditto/base.json
  src/core/timezone/config.ts
  src/core/timezone/utils.ts
  src/generated/graphql.tsx
Labels: 🐞 bug, 🥷 chore

#1570 feat: build anrok customer link in sidebar
  src/components/customers/CustomerMainInfos.tsx
  src/generated/graphql.tsx
Labels: 🛠 feature

#1574 bug: charge min amount should default to undefined if not set
  src/components/plans/ChargeAccordion.tsx
  src/core/serializers/__tests__/serializePlanInput.test.ts
  src/core/serializers/serializePlanInput.ts
  src/hooks/plans/usePlanForm.tsx
Labels: 🐞 bug
