Repository getlago/lago-front, pull requests merged in 2024-07, with the labels that each got.

#1577 misc(currency) add IRR
  src/generated/graphql.tsx
Labels: 🌈 improvement

#1581 fix: handle falsy value for name
  src/hooks/customer/useAddSubscription.tsx
Labels: 🐞 bug

#1582 feat: use new TBA connection for Netuite
  ditto/base.json
  package.json
  src/components/settings/integrations/AddNetsuiteDialog.tsx
  src/generated/graphql.tsx
  src/pages/CreditNoteDetails.tsx
  yarn.lock
Labels: 🌈 improvement

#1583 bug(combobox): fix option width when link is present
  src/components/form/ComboBox/ComboBoxItem.tsx
Labels: 🐞 bug

#1588 fix: customer details grid layout
  src/pages/CustomerDetails.tsx
Labels: 🎨 UI

#1589 feat: add link as Stripe method
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/customers/CustomerMainInfos.tsx
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/generated/graphql.tsx
Labels: 🛠 feature

#1597 bug: set correct z-index for nav elements
  src/pages/CreatePlan.tsx
  src/styles/settingsPage.tsx
Labels: 🐞 bug

#1596 misc: fix copy used for PP section
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
Labels: 🥷 chore

#1595 bug: improve charge model logic
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/types.ts
  src/hooks/plans/__tests__/fixture.ts
  src/hooks/plans/__tests__/useChargeForm.test.tsx
  src/hooks/plans/useChargeForm.tsx
Labels: 🐞 bug

#1600 misc: simple copy adjustment
  ditto/base.json
Labels: 🥷 chore

#1602 feat: implement new font system
  src/components/CodeSnippet.tsx
  src/components/designSystem/graphs/AreaChart.tsx
  src/pages/settings/EmailScenarioConfig.tsx
  src/styles/globalStyle.tsx
  src/styles/muiTheme.ts
Labels: 🌈 improvement

#1603 bug(xero): fetch accounts in payment mapping modal
  src/components/settings/integrations/XeroIntegrationMapItemDialog.tsx
  src/generated/graphql.tsx
Labels: 🐞 bug

#1605 chore(BM): query heavy calculation attribute on uniq object query
  src/components/WarningDialog.tsx
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/billableMetrics/DeleteBillableMetricDialog.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditBillableMetric.ts
  src/styles/muiTheme.ts
Labels: 🐞 bug

#1606 feat: sync invoice with Xero
  ditto/base.json
  src/components/customers/CustomerMainInfos.tsx
  src/core/constants/externalUrls.ts
  src/generated/graphql.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/InvoiceOverview.tsx
Labels: 🛠 feature

#1608 bug: prevent chain form update
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
Labels: 🐞 bug

#1612 bug: fix tab extra width
  src/components/designSystem/NavigationTab.tsx
Labels: 🐞 bug

#1614 fix: disabled field and clean form before submitting
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargeBillingRadioGroup.tsx
  src/hooks/customer/useAddSubscription.tsx
Labels: 🐞 bug

#1611 fix: refresh overdue balance query and invalidate cache
  src/components/customerPortal/PortalOverview.tsx
  src/components/customers/overview/CustomerOverview.tsx
  src/generated/graphql.tsx
Labels: ⛔️ Need Backend

#1617 fix: use organization currency as fallback
  src/components/customers/overview/CustomerOverview.tsx
Labels: 🐞 bug

#1618 feat: add disputed status in customer portal invoice item
  ditto/base.json
  ditto/de.json
  ditto/es.json
  ditto/fr.json
  ditto/it.json
  ditto/nb.json
  ditto/sv.json
  src/components/customerPortal/PortalInvoiceListItem.tsx
  src/components/designSystem/Status.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement

#1619 feat: allow to sync CN with Xero
  src/pages/CreditNoteDetails.tsx
Labels: 🛠 feature

#1622 chore: query invoice status type as array
  src/generated/graphql.tsx
  src/pages/InvoicesPage.tsx
Labels: 🥷 chore

#1621 feat: Make Xero integration enable for all customer
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/core/utils/featureFlags.ts
  src/pages/settings/Integrations.tsx
Labels: 🛠 feature

#1623 feat: turn quick filters to reusable components
  src/components/designSystem/Filters/InvoiceStatusQuickFilter.tsx
  src/components/designSystem/Filters/QuickFilters.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/index.ts
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/utils.ts
  src/components/designSystem/index.ts
  src/components/invoices/InvoicesList.tsx
  src/pages/InvoicesPage.tsx
Labels: 🛠 feature

#1620 chore: Simple DS improvement
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🌈 improvement

#1624 bug: align min spending input and button
  src/components/plans/ChargeAccordion.tsx
Labels: 🐞 bug

#1626 misc: make the quick filters wrap on resize
  src/components/designSystem/Filters/QuickFilters.tsx
Labels: 🌈 improvement
