Repository getlago/lago-front, pull requests merged in 2024-05, with the labels that each got.

#1490 chore(renovate) update schedule
  renovate.json
Labels: 🥷 chore

#1498 chore(inspectTranslations) add flag to replace TODO: copy
  scripts/InspectTranslationKeys.js
Labels: 🥷 chore

#1501 refactor(wallet): rename rule_type into trigger
  src/components/wallets/WalletCodeSnippet.tsx
  src/components/wallets/utils.ts
  src/generated/graphql.tsx
  src/pages/WalletForm.tsx
Labels: ⛔️ Need Backend

#1503 chore: fetch memberships and their organizations
  src/generated/graphql.tsx
  src/hooks/useCurrentUser.ts
  src/layouts/SideNavLayout.tsx
Labels: 🥷 chore

#1505 bug: fix invoice items aligments
  src/components/invoices/InvoiceCustomerInfos.tsx
Labels: 🐞 bug

#1504 feat: add RBAC core features
  ditto/base.json
  src/core/router/index.tsx
  src/core/router/types.ts
  src/generated/graphql.tsx
  src/hooks/__tests__/usePermissions.test.ts
  src/hooks/core/__tests__/useLocationHistory.test.ts
  src/hooks/core/useLocationHistory.ts
  src/hooks/useCurrentUser.ts
  src/hooks/usePermissions.ts
  src/layouts/SideNavLayout.tsx
  src/pages/Forbidden.tsx
  src/pages/Home.tsx
Labels: 🛠 feature

#1507 feat: add billable metrics role guard
  src/components/billableMetrics/BillableMetricItem.tsx
  src/core/router/ObjectsRoutes.tsx
  src/core/router/types.ts
  src/layouts/SideNavLayout.tsx
Labels: 🛠 feature

#1508 feat: add plan route and actions role guard
  src/components/designSystem/NavigationTab.tsx
  src/components/plans/PlanItem.tsx
  src/core/router/ObjectsRoutes.tsx
  src/hooks/core/__tests__/useLocationHistory.test.ts
  src/hooks/core/useLocationHistory.ts
  src/layouts/SideNavLayout.tsx
  src/pages/Home.tsx
  src/pages/PlanDetails.tsx
  src/pages/PlansList.tsx
Labels: 🛠 feature

#1509 feat: add addOns route and actions role guard
  src/components/addOns/AddOnItem.tsx
  src/components/plans/PlanItem.tsx
  src/core/router/ObjectsRoutes.tsx
  src/pages/AddOnDetails.tsx
  src/pages/AddOnsList.tsx
Labels: 🛠 feature

#1510 feat: add coupons route and actions role guard
  src/components/coupons/CouponItem.tsx
  src/core/router/ObjectsRoutes.tsx
  src/pages/CouponsList.tsx
Labels: 🛠 feature

#1511 misc: improve replacement regex in script
  scripts/InspectTranslationKeys.js
Labels: 🥷 chore

#1512 feat: add coupon details page
  ditto/base.json
  src/components/coupons/CouponItem.tsx
  src/components/coupons/DeleteCouponDialog.tsx
  src/components/customers/CustomerCoupons.tsx
  src/components/details/DetailsTableDisplay.tsx
  src/core/constants/form.ts
  src/core/router/ObjectsRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditCoupon.ts
  src/hooks/useCurrentUser.ts
  src/layouts/SideNavLayout.tsx
  src/pages/CouponDetails.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CustomerDetails.tsx
Labels: 🛠 feature

#1514 bug: better handling of user loading in the app
  src/hooks/core/useLocationHistory.ts
  src/hooks/useCurrentUser.ts
Labels: 🐞 bug

#1515 feat: add large batch of RBAC permission logic guard
  .vscode/lago.code-snippets
  ditto/base.json
  src/components/addOns/AddOnItem.tsx
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/customers/CustomerCreditNotesList.tsx
  src/components/customers/CustomerItem.tsx
  src/components/customers/CustomerSettings.tsx
  src/components/customers/DeleteCustomerDocumentLocaleDialog.tsx
  src/components/customers/DeleteCustomerNetPaymentTermDialog.tsx
  src/components/customers/DeleteCustomerVatRateDialog.tsx
  src/components/customers/EditCustomerDocumentLocaleDialog.tsx
  src/components/customers/EditCustomerVatRateDialog.tsx
  src/components/customers/__tests__/EditCustomerVatRateDialog.test.tsx
  src/components/customers/creditNotes/CreditNotesList.tsx
  src/components/customers/subscriptions/CustomerSubscriptionsList.tsx
  src/components/customers/subscriptions/SubscriptionLine.tsx
  src/components/invoices/InvoiceListItem.tsx
  src/components/settings/AddOrganizationVatRateDialog.tsx
  src/components/settings/emails/EmailSettingItem.tsx
  src/components/taxes/TaxItem.tsx
  src/components/wallets/CustomerWalletList.tsx
  src/core/router/CustomerRoutes.tsx
  src/core/router/DevelopperRoutes.tsx
  src/core/router/ObjectsRoutes.tsx
  src/core/router/SettingRoutes.tsx
  src/hooks/usePermissions.ts
  src/layouts/CustomerInvoiceDetails.tsx
  src/layouts/Settings.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/AddOnsList.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CouponsList.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerDetails.tsx
  src/pages/CustomersList.tsx
  src/pages/PlansList.tsx
  src/pages/settings/EmailScenarioConfig.tsx
  src/pages/settings/InvoiceSettings.tsx
  src/pages/settings/OrganizationInformations.tsx
  src/pages/settings/TaxesSettings.tsx
  src/test-utils.tsx
Labels: 🛠 feature

#1517 feat: add rbac guards for integrations page
  src/pages/settings/AdyenIntegrationDetails.tsx
  src/pages/settings/AdyenIntegrations.tsx
  src/pages/settings/GocardlessIntegrationDetails.tsx
  src/pages/settings/GocardlessIntegrations.tsx
  src/pages/settings/LagoTaxManagementIntegration.tsx
  src/pages/settings/StripeIntegrationDetails.tsx
  src/pages/settings/StripeIntegrations.tsx
Labels: 🛠 feature

#1523 misc(creditNotes): use the generic query
  src/components/customers/CustomerCreditNotesList.tsx
  src/generated/graphql.tsx
Labels: 🥷 chore
