Repository getlago/lago-front, pull requests merged in 2024-01, with the labels that each got.

#1370 misc(images) improve public images size and clean svgs
  src/public/icons/coin-dollar.svg
  src/public/icons/flash-filled.svg
  src/public/images/favicon-local.svg
  src/public/images/favicon-prod.svg
  src/public/images/favicon-staging.svg
  src/public/images/gocardless-large.svg
  src/public/images/gocardless.svg
  src/public/images/logo/lago-logo-grey.svg
  src/public/images/logo/lago-logo.svg
  src/public/images/oso.svg
Labels: 🌈 improvement

#1371 misc(breakpoint) better use helper rather than hardcoded value
  src/pages/CustomerDetails.tsx
Labels: 🌈 improvement

#1373 bug(credit-note) Prevent displaying hardcoded USD in item price
  src/generated/graphql.tsx
  src/pages/CreditNoteDetails.tsx
Labels: 🐞 bug

#1383 chore(codegen) get last graph version
  src/generated/graphql.tsx
Labels: 🥷 chore

#1382 feat(invoice) Allow to edit a draft invoice
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/invoices/details/DeleteAdjustedFeeDialog.tsx
  src/components/invoices/details/EditFeeDrawer.tsx
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduated.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePackage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineVolume.tsx
  src/components/invoices/details/InvoiceDetailsTableHeader.tsx
  src/components/invoices/details/InvoiceDetailsTablePeriodLine.tsx
  src/core/formats/__tests__/fixture.ts
  src/core/formats/__tests__/formatInvoiceItemsMap.test.ts
  src/core/formats/formatInvoiceItemsMap.ts
  src/generated/graphql.tsx
  src/pages/InvoiceOverview.tsx
Labels: 🛠 feature

#1392 bug(plan) prevent accessing undefined object
  src/components/plans/details/PlanSubscriptionList.tsx
Labels: 🐞 bug

#1393 bug(invoices) prevent faking values to wrong number by default
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePackage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineVolume.tsx
Labels: 🐞 bug

#1394 bug(rate) fix display of amount details rate
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx
Labels: 🐞 bug

#1396 bug(invoice) adjust footer td colspan for old invoices
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/components/invoices/details/InvoiceDetailsTableFooter.tsx
Labels: 🐞 bug

#1397 misc(invoice-details) improve hidden fee animation
  src/components/invoices/details/InvoiceDetailsTable.tsx
Labels: 🌈 improvement

#1399 chore(copy): Get last translations version
  ditto/base.json
Labels: 🥷 chore

#1400 bug(wallet-form) fix validation logic
  src/pages/WalletForm.tsx
Labels: 🐞 bug
