Repository getlago/lago-front, pull requests merged in 2024-10, with the labels that each got.

#1773 bug: fix icon alignment in wallet details
  src/components/wallets/WalletAccordion.tsx
Labels: 🐞 bug

#1772 bug: make search input's icon visible again
  src/components/SearchInput.tsx
Labels: 🐞 bug

#1774 bug: request payment footer button width
  src/pages/CustomerRequestOverduePayment/index.tsx
Labels: 🐞 bug

#1775 fix: overlapping tailwind classes and custom one
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/components/invoices/details/InvoiceFeeAdvanceDetailsTable.tsx
  src/components/invoices/details/InvoiceFeeArrearsDetailsTable.tsx
Labels: 🐞 bug

#1777 bug: fix few css glitch
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/form/TextInput/TextInput.tsx
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/components/plans/FixedFeeSection.tsx
  src/components/settings/EditOrganizationInvoiceNumberingDialog.tsx
  src/styles/mainObjectsForm.tsx
Labels: 🐞 bug

#1778 fix: combobox virtualized list not entirely visible
  src/styles/muiTheme.ts
Labels: 🐞 bug

#1779 fix: tooltip placement
  src/components/OverviewCard.tsx
  src/components/creditNote/CreditNoteFormCalculation.tsx
  src/components/designSystem/graphs/ChartHeader.tsx
  src/components/developers/DebuggerEventDetails.tsx
  src/components/form/ButtonSelector/ButtonSelector.tsx
  src/components/form/JsonEditor/JsonEditor.tsx
  src/components/form/Radio/RadioGroupField.tsx
  src/components/plans/GraduatedPercentageChargeTable.tsx
  src/components/wallets/WalletAccordion.tsx
Labels: 🐞 bug

#1780 bug: revert breaking css change
  src/styles/muiTheme.ts
Labels: 🐞 bug

#1781 fix: class into classname
  src/public/icons/forms/radio-checked.svg
  src/public/icons/forms/radio.svg
Labels: 🐞 bug

#1783 fix: add content-box sizing to combobox popper
  src/components/form/ComboBox/ComboBoxPopperFactory.tsx
Labels: 🐞 bug

#1771 misc: show details for all percentage fees
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/generated/graphql.tsx
Labels: 🛠 feature

#1785 refactor(selector): tailwind migration
  src/components/designSystem/Selector.tsx
  src/main.css
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/settings/Integrations.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1787 refactor: tailwind migration
  src/components/designSystem/ButtonLink.tsx
  src/components/designSystem/ShowMoreText.tsx
  src/components/designSystem/Status.tsx
  src/components/designSystem/Table/ChargeTable.tsx
  src/components/designSystem/VerticalMenu.tsx
  src/components/designSystem/__tests__/ButtonLink.test.tsx
  src/pages/BillableMetricsList.tsx
Labels: 🌈 improvement

#1788 chore: fix wrong translation
  translations/base.json
Labels: 🥷 chore

#1782 feat: add new Dynamic charge model
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargeWrapperSwitch.tsx
  src/components/plans/DynamicCharge.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/components/plans/details/PlanDetailsChargesSection.tsx
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
  src/core/constants/form.ts
  src/core/formats/intlFormatNumber.ts
  src/core/serializers/serializePlanInput.ts
  src/generated/graphql.tsx
  src/hooks/plans/__tests__/fixture.ts
  src/hooks/plans/useChargeForm.tsx
  translations/base.json
Labels: 🛠 feature

#1789 chore: copy update
  translations/base.json
Labels: 🥷 chore

#1790 misc: fix radio label allignemt
  src/components/form/Radio/Radio.tsx
Labels: 🥷 chore

#1791 feat: refactor all settings layouts
  cypress/e2e/10-resources/t10-create-taxes.cy.ts
  cypress/e2e/t20-invitations.cy.ts
  src/components/customers/CustomerSettings.tsx
  src/components/customers/EditCustomerDocumentLocaleDialog.tsx
  src/components/customers/EditCustomerInvoiceGracePeriodDialog.tsx
  src/components/customers/EditCustomerVatRateDialog.tsx
  src/components/designSystem/Selector.tsx
  src/components/designSystem/ShowMoreText.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/form/Switch/Switch.tsx
  src/components/layouts/Pages.tsx
  src/components/layouts/Settings.tsx
  src/components/settings/emails/EmailSettingItem.tsx
  src/components/settings/members/CreateInviteDialog.tsx
  src/components/settings/members/InviteItem.tsx
  src/components/settings/members/MembershipItem.tsx
  src/components/taxes/TaxItem.tsx
  src/generated/graphql.tsx
  src/pages/CustomerDetails.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/settings/Authentication/Authentication.tsx
  src/pages/settings/EmailSettings.tsx
  src/pages/settings/Integrations.tsx
  src/pages/settings/InvoiceSettings.tsx
  src/pages/settings/Members.tsx
  src/pages/settings/OrganizationInformations.tsx
  src/pages/settings/TaxesSettings.tsx
  src/styles/settingsPage.tsx
  tailwind.config.ts
  translations/base.json
Labels: 🛠 feature

#1792 bug: correct chart header text allignment
  src/components/designSystem/graphs/ChartHeader.tsx
Labels: 🐞 bug

#1793 chore: minor adjustments
  src/components/customers/CustomerSettings.tsx
  src/pages/settings/HubspotIntegrationDetails.tsx
Labels: 🌈 improvement

#1794 fix: manual dunning email preview
  src/pages/CustomerRequestOverduePayment/components/EmailPreview.tsx
Labels: 🐞 bug

#1797 chore: copy adjustment
  translations/base.json
Labels: 🥷 chore

#1796 chore: extend frame-ancestors list
  nginx/nginx.conf
Labels: 🥷 chore

#1798 fix(loading): remove fixed width
  src/components/layouts/Settings.tsx
Labels: 🐞 bug

#1800 refactor: email preview layout
  src/components/settings/LanguageSettingsButton.tsx
  src/components/settings/PreviewEmailLayout.tsx
  src/pages/settings/EmailScenarioConfig.tsx
Labels: 🌈 improvement

#1801 misc: migrate toast related components to Tailwind
  src/components/designSystem/Toasts/Toast.tsx
  src/components/designSystem/Toasts/ToastContainer.tsx
  src/core/apolloClient/reactiveVars/toastVar.ts
  tailwind.config.ts
Labels: 🌈 improvement

#1805 misc: update all filters related components to use tailwind
  src/components/designSystem/Filters/ActiveFiltersList.tsx
  src/components/designSystem/Filters/Filters.tsx
  src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx
  src/components/designSystem/Filters/FiltersPanelPoper.tsx
  src/components/designSystem/Filters/InvoiceStatusQuickFilter.tsx
  src/components/designSystem/Filters/QuickFilters.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemIssuingDate.tsx
  src/components/invoices/InvoicesList.tsx
Labels: 🌈 improvement

#1810 chore: copy update
  translations/base.json
Labels: 🥷 chore

#1806 refactor: extract dunning email component
  src/components/emails/DunningEmail.tsx
  src/components/settings/PreviewEmailLayout.tsx
  src/generated/graphql.tsx
  src/pages/CustomerRequestOverduePayment/components/EmailPreview.tsx
  src/pages/CustomerRequestOverduePayment/index.tsx
  src/styles/mainObjectsForm.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1807 feat: introduce dunnings settings
  src/components/designSystem/Chip.tsx
  src/components/designSystem/Icon/mapping.tsx
  src/components/settings/dunnings/DefaultCampaignDialog.tsx
  src/core/router/SettingRoutes.tsx
  src/generated/graphql.tsx
  src/layouts/Settings.tsx
  src/pages/settings/Dunnings/Dunnings.tsx
  src/public/icons/star-outlined-hidden.svg
  translations/base.json
Labels: ⛔️ Need Backend

#1813 misc: regroup download file methods into one util
  src/components/creditNote/CreditNotesTable.tsx
  src/components/customerPortal/PortalInvoicesList.tsx
  src/components/customers/CustomerInvoicesList.tsx
  src/components/invoices/InvoicesList.tsx
  src/core/utils/downloadFiles.ts
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerDetails.tsx
Labels: 🌈 improvement

#1812 bug(Gocardless): make sure auth popup opens on any browsers
  src/components/settings/integrations/AddGocardlessDialog.tsx
  src/core/constants/externalUrls.ts
  src/pages/settings/GocardlessIntegrationDetails.tsx
Labels: 🐞 bug

#1811 feat: create dunning campaign
  src/core/router/SettingRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/usePermissions.ts
  src/layouts/Settings.tsx
  src/pages/settings/Dunnings/CreateDunning.tsx
  src/pages/settings/Dunnings/Dunnings.tsx
  tailwind.config.ts
  translations/base.json
Labels: 🛠 feature

#1814 fix: remove duplicated keys in international translations
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nb.json
  translations/sv.json
Labels: 🌈 improvement

#1815 feat: preview email in dunning creation form
  src/components/designSystem/Drawer.tsx
  src/components/settings/dunnings/PreviewCampaignEmailDrawer.tsx
  src/generated/graphql.tsx
  src/pages/settings/Dunnings/CreateDunning.tsx
  translations/base.json
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nb.json
  translations/sv.json
Labels: 🛠 feature

#1820 bug: apply correct payment provider icon size if default
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
Labels: 🐞 bug

#1817 misc(Typography): use tailwind
  src/components/designSystem/Typography.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🌈 improvement

#1822 misc: adjust wording for more clarity
  translations/base.json
Labels: 🌈 improvement

#1827 feat: add tw merge
  src/components/designSystem/Tooltip.tsx
Labels: 🌈 improvement

#1830 misc: fix misleading copy
  translations/base.json
Labels: 🌈 improvement

#1833 misc: improve events list and details
  src/components/developers/DebuggerEventDetails.tsx
  src/components/developers/EventItem.tsx
  src/generated/graphql.tsx
  src/pages/developers/Debugger.tsx
  translations/base.json
Labels: 🌈 improvement

#1831 bug(logs): refetch should use the last args as default query
  src/pages/developers/Debugger.tsx
  src/pages/developers/WebhookLogs.tsx
Labels: 🐞 bug

#1835 bug: should manually build payload in mapping
  src/components/settings/integrations/NetsuiteIntegrationMapItemDialog.tsx
Labels: 🐞 bug

#1838 bug: manual payload forge for tax mapping
  src/components/settings/integrations/NetsuiteIntegrationMapItemDialog.tsx
Labels: 🐞 bug

#1837 deps: bump sentry package to v8
  package.json
  src/components/ErrorBoundary.tsx
  src/components/UserIdentifier.tsx
  src/core/timezone/utils.ts
  src/index.js
  yarn.lock
Labels: 🔗 dependencies

#1834 misc: some TW migration around events and webhooks
  src/components/developers/DebuggerEventDetails.tsx
  src/components/developers/EventItem.tsx
  src/components/developers/WebhookLogItem.tsx
Labels: 🌈 improvement

#1836 deps: upgrade webpack-dev-server
  package.json
  yarn.lock
Labels: 🥷 chore

#1829 fix: flacky e2e test
  cypress/cypress.config.js
  cypress/e2e/t30-create-one-off-invoice.cy.ts
Labels: 🌈 improvement, 🙅 Don't close

#1841 feat: deprecate margin props
  src/components/designSystem/Skeleton.tsx
Labels: 🌈 improvement

#1840 feat: allow to search anywhere in the combobox value
  src/components/form/ComboBox/ComboBox.tsx
  src/components/form/MultipleComboBox/MultipleComboBox.tsx
Labels: 🌈 improvement

#1843 misc: enable Hubspot integration feature
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/core/utils/featureFlags.ts
  src/pages/settings/Integrations.tsx
Labels: 🛠 feature

#1844 feat(popper): migrate to tailwind
  src/components/designSystem/Popper.tsx
Labels: 🌈 improvement
