Repository getlago/lago-front, pull requests merged in 2024-11, with the labels that each got.

#1845 misc(Skeleton): start TW migration but allow backward compatibility
  src/components/designSystem/Avatar.tsx
  src/components/designSystem/Skeleton.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🌈 improvement

#1852 misc: make sure Netsuite item's data is fully valid before flagging it as mapped
  src/components/settings/integrations/NetsuiteIntegrationItemsListDefault.tsx
Labels: 🌈 improvement

#1853 misc: migrate some Skeleton to use the new API
  src/components/OverviewCard.tsx
  src/components/SkeletonDetailsPage.tsx
  src/components/addOns/AddOnItem.tsx
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/billableMetrics/DeleteBillableMetricDialog.tsx
  src/components/coupons/CouponItem.tsx
  src/components/customerPortal/common/CustomerPortalLoading.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1823 feat: customer dunning settings
  src/components/billableMetrics/CustomExpressionDrawer.tsx
  src/components/customers/CustomerSettings.tsx
  src/components/customers/EditCustomerDunningCampaignDialog.tsx
  src/components/emails/DunningEmail.tsx
  src/generated/graphql.tsx
  src/layouts/Settings.tsx
  src/pages/settings/Dunnings/CreateDunning.tsx
  src/pages/settings/Dunnings/Dunnings.tsx
  src/styles/mainObjectsForm.tsx
  translations/base.json
Labels: 🛠 feature

#1856 bug: prevent current usage fetch for pending subscriptions
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
  src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🐞 bug

#1857 misc: remove sales order from Netsuite settings
  src/components/settings/integrations/AddNetsuiteDialog.tsx
  src/components/settings/integrations/NetsuiteIntegrationSettings.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🌈 improvement

#1860 bug: only show override modal on edit mode
  src/pages/CreatePlan.tsx
Labels: 🐞 bug

#1859 misc: refactor keys page and add actions
  src/components/designSystem/Table/Table.tsx
  src/components/designSystem/Typography.tsx
  src/components/developers/RollApiKeyDialog.tsx
  src/core/formats/__tests__/obfuscate.test.ts
  src/core/formats/obfuscate.ts
  src/generated/graphql.tsx
  src/layouts/Developers.tsx
  src/pages/developers/ApiKeys.tsx
  src/pages/developers/Webhooks.tsx
  tailwind.config.ts
  translations/base.json
Labels: 🌈 improvement

#1863 bug: use typography component for text display
  src/components/coupons/CouponItem.tsx
Labels: 🐞 bug

#1866 bug(cache): make sure to no re-fetch active queries on orga switch
  src/core/apolloClient/cacheUtils.ts
Labels: 🐞 bug

#1864 misc: allow decimal on adjusted fee amount
  src/components/invoices/details/EditFeeDrawer.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement

#1867 secu: bump eslint for CVE-2024-21539
  package.json
  yarn.lock
Labels: 🔗 dependencies

#1868 misc: update package author section
  package.json
Labels: 🥷 chore

#1870 bug: orga switch should reset cache and invalidate all active queries
  src/core/apolloClient/cacheUtils.ts
  src/hooks/useOrganizationInfos.ts
  src/layouts/SideNavLayout.tsx
Labels: 🐞 bug

#1873 misc: adapt fee copy for 1 tier graduated & percentage graduated
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduated.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx
Labels: 🌈 improvement

#1869 feat: sync invoices to Salesforce
  src/components/customers/CustomerMainInfos.tsx
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/components/settings/integrations/AddSalesforceDialog.tsx
  src/components/settings/integrations/DeleteSalesforceIntegrationDialog.tsx
  src/core/constants/externalUrls.ts
  src/core/router/SettingRoutes.tsx
  src/core/utils/featureFlags.ts
  src/generated/graphql.tsx
  src/hooks/useCreateEditCustomer.ts
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/InvoiceOverview.tsx
  src/pages/settings/Integrations.tsx
  src/pages/settings/SalesforceIntegrationDetails.tsx
  src/pages/settings/SalesforceIntegrations.tsx
  src/public/images/salesforce.svg
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend

#1874 misc(RouteWrapper): use tailwind
  src/components/RouteWrapper.tsx
Labels: 🌈 improvement

#1875 misc(CustomerPortal): display some excluding tax label when needed
  src/components/customerPortal/usage/UsagePage.tsx
  src/components/customerPortal/usage/UsageSubscriptionItem.tsx
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
  translations/base.json
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nb.json
  translations/sv.json
Labels: 🌈 improvement

#1876 refactor: move invoice settings into folder
  src/components/customers/CustomerSettings.tsx
  src/components/settings/invoices/AddOrganizationVatRateDialog.tsx
  src/components/settings/invoices/DeleteOrganizationVatRateDialog.tsx
  src/components/settings/invoices/EditDefaultCurrencyDialog.tsx
  src/components/settings/invoices/EditFinalizeZeroAmountInvoiceDialog.tsx
  src/components/settings/invoices/EditNetPaymentTermDialog.tsx
  src/components/settings/invoices/EditOrganizationDocumentLocaleDialog.tsx
  src/components/settings/invoices/EditOrganizationGracePeriodDialog.tsx
  src/components/settings/invoices/EditOrganizationInvoiceNumberingDialog.tsx
  src/components/settings/invoices/EditOrganizationInvoiceTemplateDialog.tsx
  src/core/router/SettingRoutes.tsx
  src/core/utils/invoiceNumberPreview.ts
  src/pages/settings/Invoices/InvoiceSettings.tsx
Labels: 🌈 improvement

#1879 feat: migrate button to tailwind
  src/components/designSystem/Button.tsx
Labels: 🌈 improvement

#1880 misc(Accordion): Use tailwind internally
  src/components/designSystem/Accordion.tsx
  src/styles/muiTheme.ts
  tailwind.config.ts
Labels: 🌈 improvement

#1883 bug(Accordion): make sure noContentMargin condition overrides
  src/components/designSystem/Accordion.tsx
Labels: 🐞 bug

#1871 feat: edit/delete dunnings
  src/components/settings/dunnings/DeleteCampaignDialog.tsx
  src/core/router/SettingRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditDunningCampaign.ts
  src/layouts/Settings.tsx
  src/pages/settings/Dunnings/CreateDunning.tsx
  src/pages/settings/Dunnings/Dunnings.tsx
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend

#1884 refactor: remove usage of ButtonGroup
  src/components/designSystem/Dialog.tsx
  src/components/form/ButtonSelector/ButtonSelector.tsx
  src/pages/CreateCoupon.tsx
  src/styles/designSystem/ButtonGroup.tsx
  src/styles/designSystem/index.ts
Labels: 🌈 improvement

#1872 feat: manage multiple api keys
  src/components/designSystem/Skeleton.tsx
  src/components/developers/DeleteApiKeyDialog.tsx
  src/components/developers/RollApiKeyDialog.tsx
  src/components/developers/RotateApiKeyDialog.tsx
  src/components/layouts/Pages.tsx
  src/core/router/ObjectsRoutes.tsx
  src/generated/graphql.tsx
  src/layouts/Developers.tsx
  src/pages/developers/ApiKeys.tsx
  src/pages/developers/ApiKeysForm.tsx
  src/pages/settings/Authentication/Authentication.tsx
  src/pages/settings/Dunnings/Dunnings.tsx
  src/pages/settings/EmailSettings.tsx
  src/pages/settings/Integrations.tsx
  src/pages/settings/Invoices/InvoiceSettings.tsx
  src/pages/settings/Members.tsx
  src/pages/settings/OrganizationInformations.tsx
  src/pages/settings/TaxesSettings.tsx
  tailwind.config.ts
  translations/base.json
Labels: 🛠 feature

#1885 deps: remove resolutions and update some packages
  package.json
  yarn.lock
Labels: 🔗 dependencies

#1889 bug(Skeleton): prevent non text loading to take full width
  src/components/designSystem/Skeleton.tsx
Labels: 🐞 bug

#1886 misc: remove MUI warning
  src/styles/muiTheme.ts
Labels: 🥷 chore

#1891 misc: recast type to remove ts expected error comment
  src/core/apolloClient/init.ts
Labels: 🥷 chore

#1894 bug: wrong interaction style definition
  src/styles/muiTheme.ts
Labels: 🐞 bug

#1895 bug: adjust styles that been broken after recent package bump
  src/components/form/ButtonSelector/TabButton.tsx
  src/components/form/Switch/Switch.tsx
Labels: 🐞 bug
