Repository getlago/lago-front, pull requests merged in 2024-09, with the labels that each got.

#1711 refactor: fetch integrations inside useOrganizationInfos hook
  src/components/plans/ProgressiveBillingSection.tsx
  src/generated/graphql.tsx
  src/hooks/useOrganizationInfos.ts
  src/pages/settings/Authentication/Authentication.tsx
  src/pages/settings/Integrations.tsx
Labels: 🌈 improvement

#1709 fix: migrate to snippet builder
  src/components/billableMetrics/BillableMetricCodeSnippet.tsx
  src/core/utils/snippetBuilder.ts
Labels: 🐞 bug

#1710 bug: better condition for Anrok sync actions
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/InvoiceOverview.tsx
  translations/base.json
Labels: 🐞 bug

#1702 misc(integrations): Anrok hidden behind premium flag
  src/components/plans/ProgressiveBillingSection.tsx
  src/generated/graphql.tsx
  src/pages/settings/Authentication/Authentication.tsx
  src/pages/settings/Integrations.tsx
Labels: 🌈 improvement, ⛔️ Need Backend

#1712 misc: make sure redirection is not lost after outside navigation
  src/core/apolloClient/cacheUtils.ts
  src/hooks/core/useLocationHistory.ts
  src/pages/Home.tsx
Labels: 🥷 chore

#1713 misc: request smaller amount of data on retryAllInvoicePayments
  src/generated/graphql.tsx
  src/pages/InvoicesPage.tsx
Labels: 🥷 chore

#1716 misc: customer name should not be mandatory as on BE
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
Labels: 🌈 improvement

#1723 feat(InlineBarsChart): add new tooltip on hover API
  src/components/designSystem/graphs/InlineBarsChart.tsx
Labels: 🥷 chore

#1721 chore: change default table rowSize
  src/components/designSystem/Table/Table.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/__devOnly/fixtures.ts
Labels: 🛠 feature, 🥷 chore

#1722 misc(ChartHeader): set some attributes as optional
  src/components/designSystem/graphs/ChartHeader.tsx
Labels: 🥷 chore

#1724 misc(deps): make sure we use the fixed CVE for micromatch
  yarn.lock
Labels: 🔗 dependencies

#1725 misc: update generated graph with last BE version
  src/generated/graphql.tsx
Labels: 🥷 chore

#1726 misc(NavigationTab) update the API to allow leftSpacing object
  src/components/designSystem/NavigationTab.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/layouts/Developers.tsx
  src/pages/CustomerDetails.tsx
  src/pages/InvoicesPage.tsx
  src/pages/PlanDetails.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/settings/AnrokIntegrationDetails.tsx
  src/pages/settings/NetsuiteIntegrationDetails.tsx
  src/pages/settings/XeroIntegrationDetails.tsx
Labels: 🌈 improvement

#1728 chore: update PR template to mention Linear ID instead of canny
  .github/pull_request_template.md
Labels: 🥷 chore

#1729 feat: intl support
  scripts/translations/add.js
Labels: 🌈 improvement

#1719 chore: enable back cypress
  .github/workflows/cypress.old
  .github/workflows/cypress.yml
  .gitignore
  .prettierignore
  ci/docker-compose.ci.yml
  cypress.config.ts
  cypress/cypress.config.js
  cypress/e2e/00-auth/t0-signup.cy.ts
  cypress/e2e/00-auth/t10-login.cy.ts
  cypress/e2e/10-resources/t10-create-taxes.cy.ts
  cypress/e2e/10-resources/t20-create-customer.cy.ts
  cypress/e2e/10-resources/t30-create-bm.cy.ts
  cypress/e2e/10-resources/t40-create-plan.cy.ts
  cypress/e2e/10-resources/t50-edit-plan.cy.ts
  cypress/e2e/10-resources/t60-coupons-create-edit-apply.cy.ts
  cypress/e2e/10-resources/t70-addon-create-edit.cy.ts
  cypress/e2e/t10-add-subscription.cy.ts
  cypress/e2e/t20-invitations.cy.ts
  cypress/e2e/t30-create-one-off-invoice.cy.ts
  cypress/support/e2e.ts
  cypress/support/index.d.ts
  cypress/support/reusableConstants.ts
  docker-compose.ci.yml
  package.json
  src/components/customers/overview/CustomerOverview.tsx
  src/components/designSystem/Status.tsx
  src/components/form/DatePicker/DatePicker.tsx
  src/components/settings/members/InviteItem.tsx
  src/pages/AddOnDetails.tsx
  src/pages/CouponDetails.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CustomerDetails.tsx
  src/pages/SubscriptionDetails.tsx
  src/pages/settings/Members.tsx
  yarn.lock
Labels: 🌈 improvement, 🧪 testing

#1735 fix: add-on snippet and usage or snippet builder
  src/components/addOns/AddOnCodeSnippet.tsx
  src/components/coupons/CouponCodeSnippet.tsx
  src/components/plans/PlanCodeSnippet.tsx
  src/components/taxes/TaxCodeSnippet.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateTax.tsx
Labels: 🐞 bug

#1651 feat: request payment page
  src/components/OverviewCard.tsx
  src/components/customers/overview/CustomerOverview.tsx
  src/components/graphs/Gross.tsx
  src/core/apolloClient/graphqlResolvers.tsx
  src/core/router/CustomerRoutes.tsx
  src/core/timezone/utils.ts
  src/generated/graphql.tsx
  src/hooks/usePermissions.ts
  src/pages/CustomerDetails.tsx
  src/pages/CustomerRequestOverduePayment/__tests__/validateEmails.test.ts
  src/pages/CustomerRequestOverduePayment/components/EmailPreview.tsx
  src/pages/CustomerRequestOverduePayment/components/FreemiumAlert.tsx
  src/pages/CustomerRequestOverduePayment/components/RequestPaymentForm.tsx
  src/pages/CustomerRequestOverduePayment/index.tsx
  src/pages/CustomerRequestOverduePayment/validateEmails.ts
  translations/base.json
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nb.json
  translations/sv.json
Labels: ⛔️ Need Backend

#1727 feat: add new subscription usage tab with current usage table
  src/components/customers/usage/CustomerUsage.tsx
  src/components/customers/usage/CustomerUsageDetailDrawer.tsx
  src/components/customers/usage/SubscriptionUsageDetailDrawer.tsx
  src/components/customers/usage/UsageItem.tsx
  src/components/designSystem/Drawer.tsx
  src/components/designSystem/Skeleton.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/plans/StandardCharge.tsx
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
  src/components/subscriptions/SubscriptionUsageTabContent.tsx
  src/generated/graphql.tsx
  src/pages/CustomerDetails.tsx
  src/pages/SubscriptionDetails.tsx
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend

#1738 bug: multiple adjustments on the customer usage
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🐞 bug

#1742 bug: slight improvement for home redirection
  src/pages/Home.tsx
Labels: 🐞 bug

#1741 feat: add lifetime usage graph to sub details
  src/components/designSystem/graphs/fixtures.ts
  src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx
  src/components/subscriptions/SubscriptionUsageTabContent.tsx
  src/components/subscriptions/__tests__/utils.test.ts
  src/components/subscriptions/utils.ts
  src/generated/graphql.tsx
  src/hooks/customer/useAddSubscription.tsx
  src/hooks/plans/usePlanForm.tsx
  src/pages/CreatePlan.tsx
  src/pages/CreateSubscription.tsx
  src/pages/SubscriptionDetails.tsx
  translations/base.json
Labels: 🛠 feature

#1747 misc: fix focus ring cropped from container
  src/components/plans/ProgressiveBillingSection.tsx
Labels: 🌈 improvement

#1746 deps: general reinstall of all dependencies using yarn
  yarn.lock
Labels: 🔗 dependencies

#1752 misc: remove classnames and use cx feature from cva
  .vscode/lago.code-snippets
  package.json
  src/components/designSystem/Alert.tsx
  src/components/designSystem/Button.tsx
  src/components/designSystem/ButtonLink.tsx
  src/components/designSystem/Icon/Icon.tsx
  src/components/designSystem/Skeleton.tsx
  src/components/designSystem/Toasts/Toast.tsx
  src/components/form/Checkbox/Checkbox.tsx
  src/components/form/ComboBox/ComboBoxInput.tsx
  src/components/form/ComboBox/ComboBoxItem.tsx
  src/components/form/ComboBox/ComboBoxPopperFactory.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxItem.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxPopperFactory.tsx
  src/components/form/Radio/Radio.tsx
  src/components/form/Switch/Switch.tsx
  src/styles/utils.ts
  yarn.lock
Labels: 🌈 improvement

#1753 bug: fix redirection stuck on home white page
  src/pages/Home.tsx
Labels: 🐞 bug

#1754 misc: fix icon alignment and migrate component to tailwind
  src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx
Labels: 🌈 improvement

#1755 misc: tailwind eslint
  .eslintrc
  package.json
  src/components/CodeSnippet.tsx
  src/components/customers/usage/CustomerUsage.tsx
  src/components/designSystem/Avatar.tsx
  src/components/designSystem/Filters/FiltersPanelPoper.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemIssuingDate.tsx
  src/components/designSystem/NavigationTab.tsx
  src/components/designSystem/graphs/InlineBarsChart.tsx
  src/components/form/Checkbox/Checkbox.tsx
  src/components/form/DatePicker/DatePicker.tsx
  src/components/form/JsonEditor/JsonEditor.tsx
  src/components/form/Radio/Radio.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduated.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePackage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineVolume.tsx
  src/components/invoices/details/InvoiceFeeAdvanceDetailsTable.tsx
  src/components/invoices/details/InvoiceFeeArrearsDetailsTable.tsx
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
  src/components/plans/details/PlanSubscriptionList.tsx
  src/components/settings/EditOrganizationInvoiceNumberingDialog.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/Analytics.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/WalletForm/components/TopUpCard.tsx
  yarn.lock
Labels: 🌈 improvement

#1750 refactor: split graphql definitions into two schemas
  .env.template
  .github/workflows/codegen.yml
  codegen.yml
  src/generated/graphql.tsx
Labels: ⛔️ Need Backend

#1759 secu: add nginx header config for CSP frame-ancestors
  nginx/nginx.conf
Labels: 🥷 chore

#1757 fix: success toast for xero sync
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/CreditNoteDetails.tsx
  translations/base.json
Labels: 🐞 bug

#1762 misc: revert graphql split
  .env.template
  .github/workflows/codegen.yml
  codegen.yml
  src/generated/graphql.tsx
Labels: 🥷 chore

#1763 feat: new tax system for netsuite
  src/components/settings/integrations/IntegrationItemLine.tsx
  src/components/settings/integrations/NetsuiteIntegrationItemsList.tsx
  src/components/settings/integrations/NetsuiteIntegrationItemsListDefault.tsx
  src/components/settings/integrations/NetsuiteIntegrationMapItemDialog.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🛠 feature

#1760 fix: set svg to inline-block
  src/main.css
Labels: 🐞 bug

#1769 misc: add new domains to nginx frame ancestor CSP
  nginx/nginx.conf
Labels: 🥷 chore

#1768 chore: some Tailwind component migration
  src/components/addOns/AddOnItem.tsx
  src/components/billableMetrics/BillableMetricItem.tsx
  src/components/coupons/AddBillableMetricToCouponDialog.tsx
  src/components/coupons/AddPlanToCouponDialog.tsx
  src/components/customers/CustomerCreditNotesList.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1764 misc: enable hot reloading with fast refresh
  .babelrc
  .babelrc.js
  package.json
  webpack.dev.js
  yarn.lock
Labels: 🌈 improvement
