Repository getlago/lago-front, pull requests merged in 2024-08, with the labels that each got.

#1635 misc: change docker compose run command in CI
  .github/workflows/codegen.yml
Labels: 🥷 chore

#1636 misc: fix some button alignment in plan form
  src/components/plans/ChargePercentage.tsx
  src/components/plans/StandardCharge.tsx
Labels: 🥷 chore

#1631 feat: add settings for no invoice top-up
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/wallets/TopupWalletDialog.tsx
  src/components/wallets/WalletCodeSnippet.tsx
  src/generated/graphql.tsx
  src/pages/WalletForm/WalletForm.tsx
  src/pages/WalletForm/components/TopUpCard.tsx
Labels: ⛔️ Need Backend

#1638 bug: change wrong disabled condition for charge option
  src/components/plans/ChargeAccordion.tsx
Labels: 🐞 bug

#1639 feat: migrate list item into table component
  src/components/customerPortal/PortalInvoiceListItem.tsx
  src/components/customerPortal/PortalInvoicesList.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement

#1633 feat: Add filters panel in invoice page
  ditto/base.json
  ditto/config.yml
  ditto/index.js
  src/components/designSystem/Filters/ActiveFiltersList.tsx
  src/components/designSystem/Filters/Filters.tsx
  src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx
  src/components/designSystem/Filters/FiltersPanelPoper.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/filtersElements/FiltersItemCurrency.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemCustomer.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemInvoiceType.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemIssuingDate.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentDisputeLost.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentOverdue.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/utils.ts
  src/components/form/DatePicker/DatePicker.tsx
  src/components/invoices/InvoicesList.tsx
  src/generated/graphql.tsx
  src/pages/InvoicesPage.tsx
  src/styles/muiTheme.ts
Labels: 🛠 feature

#1641 bug: make sure input is full width on error
  src/components/designSystem/Filters/filtersElements/FiltersItemIssuingDate.tsx
Labels: 🐞 bug

#1643 bug: remove unnecessary zindex rule
  src/styles/muiTheme.ts
Labels: 🐞 bug, 🥷 chore

#1642 fix: use paymentDisputeLostAt instead of paymentDisputeLosable
  src/components/customerPortal/PortalInvoicesList.tsx
  src/generated/graphql.tsx
Labels: 🐞 bug

#1644 misc: adjust some copies
  ditto/base.json
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
Labels: 🥷 chore

#1645 misc: small buttons should have caption style
  src/styles/muiTheme.ts
Labels: 🥷 chore

#1649 bug(Checkbox): align label with box
  src/components/form/Checkbox/Checkbox.tsx
Labels: 🐞 bug

#1652 misc: Alert can be fullwidth with custom v-padding
  src/components/designSystem/Alert.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🌈 improvement

#1653 feat: display alerts if tax provider is present
  ditto/base.json
  src/components/settings/integrations/AddLagoTaxManagementDialog.tsx
  src/generated/graphql.tsx
  src/hooks/useIntegrations.ts
  src/pages/settings/TaxesSettings.tsx
Labels: 🛠 feature

#1654 bug(filters): display picker on top and filter multiple values
  src/components/designSystem/Filters/filtersElements/FiltersItemInvoiceType.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx
  src/styles/muiTheme.ts
Labels: 🐞 bug

#1655 misc: use gap spacing
  src/pages/CustomersList.tsx
Labels: 🥷 chore

#1656 feat: Salesforce iframe navigation
  src/core/apolloClient/reactiveVars/locationHistoryVar.ts
  src/hooks/core/useLocationHistory.ts
  src/hooks/customer/useAddSubscription.tsx
  src/hooks/useSalesForceConfig.ts
  src/pages/CreateInvoice.tsx
  src/pages/CreateSubscription.tsx
  src/pages/InvitationInit.tsx
  src/pages/auth/Login.tsx
Labels: 🛠 feature

#1640 feat: export invoices
  ditto/base.json
  src/components/form/Radio/RadioGroupField.tsx
  src/components/invoices/ExportInvoicesDialog.tsx
  src/generated/graphql.tsx
  src/pages/InvoicesPage.tsx
Labels: 🛠 feature

#1659 chore: remove linter warning
  src/components/customerPortal/PortalOverview.tsx
Labels: 🥷 chore

#1662 feat: retry Anrok invoice sync on failed ones
  ditto/base.json
  src/components/settings/integrations/AnrokIntegrationSettings.tsx
  src/generated/graphql.tsx
Labels: 🛠 feature

#1664 misc: sticky bar for one-off form
  src/pages/CreateInvoice.tsx
  src/styles/mainObjectsForm.tsx
Labels: 🌈 improvement

#1663 bug: better min commitment accordion display
  src/components/plans/details/PlanDetailsCommitmentsSection.tsx
Labels: 🐞 bug

#1669 bug(NagivationTab): prevent min height if no children
  src/components/designSystem/NavigationTab.tsx
Labels: 🐞 bug

#1670 misc: new translations scripts
  .github/workflows/linter.yml
  package.json
  scripts/translations/add.js
  scripts/translations/inspect.js
Labels: 🥷 chore

#1673 chore: remove Ditto words
  .eslintignore
  .github/workflows/translation-update.yml
  .gitignore
  .prettierignore
  ditto/config.yml
  ditto/index.d.ts
  ditto/index.js
  package.json
  scripts/MergeTranslationFiles.js
  scripts/translations/add.js
  scripts/translations/inspect.js
  src/core/translations/types.ts
  src/core/translations/utils.ts
  src/hooks/core/useContextualLocale.ts
  translations/base.json
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nb.json
  translations/sv.json
  yarn.lock
Labels: 🥷 chore, 🔗 dependencies

#1684 misc: refactor plan advanced settings section
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
  src/components/plans/details/PlanDetailsCommitmentsSection.tsx
  src/components/plans/details/PlanDetailsOverview.tsx
Labels: 🥷 chore

#1685 misc: resolve ws security issue
  package.json
  src/generated/graphql.tsx
  yarn.lock
Labels: 🔗 dependencies

#1686 bug(navigationTab) fix max height falsy value
  src/components/designSystem/NavigationTab.tsx
Labels: 🐞 bug

#1692 chore: fix ws deep package version
  package.json
  src/generated/graphql.tsx
  yarn.lock
Labels: 🥷 chore, 🔗 dependencies

#1693 bug(plan details) fix minimum commitment display condition
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
Labels: 🐞 bug

#1694 chore: align wording related to connections
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  translations/base.json
Labels: 🥷 chore

#1683 feat: tie our systems with Anrok taxes
  src/components/creditNote/CreditNoteFormCalculation.tsx
  src/components/creditNote/__tests__/fixtures.ts
  src/components/creditNote/types.ts
  src/components/customers/CustomerInvoicesList.tsx
  src/components/customers/CustomerInvoicesTab.tsx
  src/components/customers/usage/UsageItem.tsx
  src/components/designSystem/Icon/Icon.tsx
  src/components/designSystem/Status.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/invoices/FinalizeInvoiceDialog.tsx
  src/components/invoices/InvoiceCreditNotesTable.tsx
  src/components/invoices/InvoiceCustomerInfos.tsx
  src/components/invoices/InvoicesList.tsx
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/invoices/details/InvoiceDetailsTableFooter.tsx
  src/core/constants/externalUrls.ts
  src/core/constants/form.ts
  src/core/constants/statusInvoiceMapping.ts
  src/core/serializers/__tests__/serializeCreditNoteInput.test.ts
  src/generated/graphql.tsx
  src/hooks/useCreateCreditNote.ts
  src/hooks/useIntegrations.ts
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/InvoiceOverview.tsx
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend, 👀 QA

#1696 feat: progressive billing (plan + subscription)
  src/components/designSystem/Table/ChargeTable.tsx
  src/components/invoices/details/InvoiceDetailsTableFooter.tsx
  src/components/plans/CommitmentsSection.tsx
  src/components/plans/ProgressiveBillingSection.tsx
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
  src/components/plans/types.ts
  src/core/constants/externalUrls.ts
  src/core/serializers/__tests__/serializePlanInput.test.ts
  src/core/serializers/serializePlanInput.ts
  src/generated/graphql.tsx
  src/hooks/plans/usePlanForm.tsx
  src/hooks/plans/useProgressiveBillingForm.tsx
  src/pages/CreatePlan.tsx
  src/pages/CreateSubscription.tsx
  translations/base.json
Labels: 🛠 feature

#1697 misc(rate): default display up to 4 digit unless override
  src/components/coupons/CouponCaption.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/customers/CustomerSettings.tsx
  src/components/customers/EditCustomerVatRateDialog.tsx
  src/components/form/AmountInput/AmountInput.tsx
  src/components/form/TextInput/__tests__/FormatValue.test.ts
  src/components/invoices/EditInvoiceItemTaxDialog.tsx
  src/components/invoices/InvoiceCreditNotesTable.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduated.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePackage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineVolume.tsx
  src/components/invoices/details/InvoiceDetailsTableFooter.tsx
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/CommitmentsSection.tsx
  src/components/plans/FixedFeeSection.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/components/plans/details/PlanDetailsChargesSection.tsx
  src/components/plans/details/PlanDetailsFixedFeeAccordion.tsx
  src/components/settings/AddOrganizationVatRateDialog.tsx
  src/components/taxes/TaxItem.tsx
  src/core/formats/__tests__/intlFormatNumber.test.ts
  src/core/formats/intlFormatNumber.ts
  src/pages/AddOnDetails.tsx
  src/pages/CouponDetails.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreateTax.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/settings/InvoiceSettings.tsx
  src/pages/settings/LagoTaxManagementIntegration.tsx
Labels: 🌈 improvement

#1701 chore(createInvoice): nicely display Anrok tax error
  src/generated/graphql.tsx
  src/pages/CreateInvoice.tsx
Labels: 🥷 chore, ⛔️ Need Backend

#1703 misc: prevent rendering broken links
  src/components/subscriptions/SubscriptionInformations.tsx
  src/pages/PlanDetails.tsx
Labels: 🐞 bug

#1706 bug(oneOffInvoice) fix tax display from provider
  src/pages/CreateInvoice.tsx
Labels: 🐞 bug
