Repository getlago/lago-front, pull requests merged in 2024-12, with the labels that each got.

#1897 misc: make sure we control filter values displayed
  src/components/designSystem/Filters/filtersElements/FiltersItemInvoiceType.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx
  translations/base.json
Labels: 🐞 bug

#1899 refactor: card tailwind migration
  src/components/OverviewCard.tsx
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
  src/components/designSystem/Card.tsx
  src/components/designSystem/index.ts
  src/components/invoices/AddMetadataDrawer.tsx
  src/components/invoices/details/EditFeeDrawer.tsx
  src/components/plans/ChargesSection.tsx
  src/components/plans/EditCustomChargeDrawer.tsx
  src/components/plans/FixedFeeSection.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreateCreditNote.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreatePlan.tsx
  src/pages/CreateSubscription.tsx
  src/pages/CreateTax.tsx
  src/pages/CustomerRequestOverduePayment/components/EmailPreview.tsx
  src/pages/WalletForm/components/LoadingView.tsx
  src/pages/WalletForm/components/SettingsCard.tsx
  src/pages/WalletForm/components/TopUpCard.tsx
  src/styles/designSystem/Card.tsx
  src/styles/designSystem/index.ts
Labels: 🌈 improvement

#1902 feat: migrate code snippet component
  src/components/CodeSnippet.tsx
  src/components/CodeSnippet/CodeSnippet.tsx
  src/components/CodeSnippet/codeSnippet.css
  src/components/CodeSnippet/index.ts
  tailwind.config.ts
Labels: 🌈 improvement

#1903 fix: migrate styled(Button)
  src/components/OrganizationLogoPicker.tsx
  src/components/PremiumWarningDialog.tsx
  src/components/form/ComboBox/ComboBoxInput.tsx
  src/components/form/DatePicker/DatePicker.tsx
  src/components/invoices/EditInvoiceItemTaxDialog.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/GraduatedPercentageChargeTable.tsx
  src/components/plans/ProgressiveBillingSection.tsx
  src/components/plans/VolumeChargeTable.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/layouts/Settings.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/CustomerDetails.tsx
  src/pages/WalletForm/WalletForm.tsx
  src/pages/auth/ResetPassword.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1904 misc(Table): migrate to Tailwind
  src/components/designSystem/Table/Table.tsx
  src/core/utils/__tests__/responsiveProps.test.ts
  src/core/utils/responsiveProps.ts
  tailwind.config.ts
Labels: 🌈 improvement

#1905 refactor: split add customer drawer
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
  src/components/customers/addDrawer/BillingAccordion.tsx
  src/components/customers/addDrawer/MetadataAccordion.tsx
Labels: 🌈 improvement

#1907 misc: fix some ts warnings
  src/components/coupons/AddBillableMetricToCouponDialog.tsx
  src/components/coupons/AddPlanToCouponDialog.tsx
  src/components/invoices/EditInvoiceDisplayName.tsx
  src/components/invoices/EditInvoiceItemDescriptionDialog.tsx
  src/pages/CreateCreditNote.tsx
Labels: 🥷 chore

#1906 refactor: tooltip migration
  src/components/TimezoneDate.tsx
  src/components/creditNote/CreditNoteFormItem.tsx
  src/components/customers/overview/CustomerCoupons.tsx
  src/components/form/AmountInput/AmountInputField.tsx
  src/components/invoices/AddMetadataDrawer.tsx
  src/components/plans/FixedFeeSection.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreateSubscription.tsx
  src/pages/CreateTax.tsx
  src/pages/WalletForm/components/SettingsCard.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1908 misc(TextInput): migrate to Tailwind
  src/components/form/TextInput/TextInput.tsx
Labels: 🌈 improvement

#1893 feat: manage api keys permission in form
  src/components/developers/RotateApiKeyDialog.tsx
  src/components/form/Checkbox/Checkbox.tsx
  src/components/form/Radio/Radio.tsx
  src/core/apolloClient/graphqlResolvers.tsx
  src/generated/graphql.tsx
  src/pages/developers/ApiKeysForm.tsx
  translations/base.json
Labels: 🛠 feature

#1909 feat: add tdCellClassName in table columns
  src/components/creditNote/CreditNotesTable.tsx
  src/components/designSystem/Table/Table.tsx
Labels: 🐞 bug

#1911 bug: prevent deletion of default filter price in subscription form
  src/components/plans/ChargeAccordion.tsx
  translations/base.json
Labels: 🐞 bug

#1912 misc(ButtonSelector): migrate to tailwind
  src/components/form/ButtonSelector/ButtonSelector.tsx
Labels: 🌈 improvement

#1914 misc: migrate some components to tailwind
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/customers/CustomerInvoicesList.tsx
  src/components/customers/CustomerInvoicesTab.tsx
Labels: 🌈 improvement

#1913 misc(AmountInput): migrate to Tailwind
  src/components/form/AmountInput/AmountInput.tsx
  src/components/form/AmountInput/AmountInputField.tsx
Labels: 🌈 improvement

#1915 fix: use string instead of number to avoid scientific notation
  src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx
  src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx
  src/hooks/plans/useGraduatedChargeForm.ts
  src/hooks/plans/useVolumeChargeForm.ts
Labels: 🐞 bug

#1921 refactor: migrate switch to tailwind
  src/components/form/Switch/Switch.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1923 refactor: migrate radio to tailwind
  src/components/form/Radio/Radio.tsx
  src/components/form/Radio/RadioField.tsx
  src/components/form/Radio/RadioIcon.tsx
  src/public/icons/forms/radio-checked.svg
  src/public/icons/forms/radio.svg
Labels: 🌈 improvement

#1924 refactor: migrate json editor component
  __mocks__/styleMock.js
  jest.config.js
  src/components/form/JsonEditor/JsonEditor.tsx
  src/components/form/JsonEditor/jsonEditor.css
Labels: 🌈 improvement

#1926 refactor: migrate checkbox component
  src/components/form/Checkbox/Checkbox.tsx
  src/components/form/Checkbox/CheckboxIcon.tsx
  src/public/icons/forms/checkbox-checked.svg
  src/public/icons/forms/checkbox-indeterminate.svg
  src/public/icons/forms/checkbox.svg
Labels: 🌈 improvement

#1925 feat: revamp customers list
  cypress/e2e/10-resources/t50-edit-plan.cy.ts
  cypress/e2e/10-resources/t60-coupons-create-edit-apply.cy.ts
  cypress/e2e/t10-add-subscription.cy.ts
  cypress/e2e/t30-create-one-off-invoice.cy.ts
  src/components/GenericPlaceholder.tsx
  src/components/PaymentProviderChip.tsx
  src/components/customers/CustomerItem.tsx
  src/components/customers/DeleteCustomerDialog.tsx
  src/components/designSystem/Table/Table.tsx
  src/generated/graphql.tsx
  src/pages/CustomerDetails.tsx
  src/pages/CustomersList.tsx
  translations/base.json
Labels: 🌈 improvement

#1934 deps: fix CVE path-to-regexp
  package.json
  yarn.lock
Labels: 🔗 dependencies

#1936 refactor: use centered layout for dunnings
  src/components/layouts/Pages.tsx
  src/pages/developers/ApiKeysForm.tsx
  src/pages/settings/Dunnings/CreateDunning.tsx
  src/styles/mainObjectsForm.tsx
Labels: 🌈 improvement

#1918 feat: preview custom section
  src/components/settings/invoices/PreviewCustomSectionDrawer.tsx
  src/generated/graphql.tsx
  src/pages/settings/Invoices/CreateCustomSection.tsx
  translations/base.json
Labels: 🛠 feature

#1917 feat: create invoice custom section
  src/components/settings/invoices/DefaultCustomSectionDialog.tsx
  src/components/settings/invoices/PreviewCustomSectionDrawer.tsx
  src/core/router/SettingRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditInvoiceCustomSection.ts
  src/layouts/Settings.tsx
  src/pages/settings/Invoices/CreateCustomSection.tsx
  translations/base.json
Labels: 🛠 feature

#1938 misc: some TW migration and refactor
  src/components/OrganizationLogoPicker.tsx
  src/components/customers/subscriptions/SubscriptionItem.tsx
  src/components/customers/usage/CustomerUsage.tsx
  translations/base.json
Labels: 🌈 improvement

#1939 feat: create hyperlink for stripe customer in sidebar
  src/components/customers/CustomerMainInfos.tsx
  src/core/constants/externalUrls.ts
Labels: 🌈 improvement

#1941 feat: new accordion variant
  src/components/designSystem/Accordion.tsx
  src/components/designSystem/Icon/mapping.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/public/icons/chevron-down-filled.svg
  src/public/icons/chevron-right-filled.svg
  src/styles/muiTheme.ts
Labels: 🛠 feature

#1945 misc: improve multiple combobox behaviour
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx
  src/components/form/MultipleComboBox/MultipleComboBox.tsx
Labels: 🌈 improvement

#1947 misc: migrate multiple combobox to tailwind
  src/components/form/ComboBox/ComboBox.tsx
  src/components/form/ComboBox/ComboBoxPopperFactory.tsx
  src/components/form/ComboBox/ComboboxList.tsx
  src/components/form/MultipleComboBox/MultipleComboBox.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxItemWrapper.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxList.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxPopperFactory.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxVirtualizedList.tsx
  src/components/form/MultipleComboBox/types.ts
Labels: 🌈 improvement

#1948 misc: migrate styled typography to tailwind part I
  src/components/customers/CustomerMainInfos.tsx
  src/components/customers/subscriptions/SubscriptionLine.tsx
  src/components/designSystem/Alert.tsx
  src/components/developers/CreateWebhookDialog.tsx
  src/components/developers/WebhookLogDetails.tsx
  src/components/form/ButtonSelector/TabButton.tsx
  src/components/invoices/EditInvoiceItemTaxDialog.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/CommitmentsSection.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/GraduatedPercentageChargeTable.tsx
  src/components/plans/PlanItem.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/components/plans/ProgressiveBillingSection.tsx
  src/components/plans/VolumeChargeTable.tsx
  src/components/settings/members/CreateInviteDialog.tsx
  src/components/wallets/WalletAccordion.tsx
  src/components/wallets/WalletTransactionListItem/ListItem.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/AddOnsList.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1951 bug: make sure className is passed to all Skeleton cases
  src/components/designSystem/Skeleton.tsx
Labels: 🐞 bug

#1950 misc: refactor shared styled typography to render FC with TW
  src/components/customers/CustomerCreditNotesList.tsx
  src/components/customers/overview/CustomerCoupons.tsx
  src/components/customers/overview/CustomerOverview.tsx
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/components/wallets/CustomerWalletList.tsx
  src/pages/CreateTax.tsx
  src/pages/Invitation.tsx
  src/pages/auth/ForgotPassword.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/SignUp.tsx
  src/styles/auth.tsx
  src/styles/customer.tsx
  src/styles/detailsPage.tsx
  src/styles/mainObjectsForm.tsx
Labels: 🌈 improvement

#1952 misc: migrate all styled icon to use tailwind
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargeBillingRadioGroup.tsx
  src/components/plans/CommitmentsSection.tsx
  src/components/plans/ProgressiveBillingSection.tsx
  src/layouts/SideNavLayout.tsx
Labels: 🌈 improvement

#1937 feat: handle invoice tax status pending
  src/components/customers/CustomerInvoicesList.tsx
  src/components/customers/CustomerInvoicesTab.tsx
  src/components/invoices/InvoicesList.tsx
  src/components/invoices/details/InvoiceDetailsTableFooter.tsx
  src/core/constants/statusInvoiceMapping.ts
  src/generated/graphql.tsx
  src/layouts/CustomerInvoiceDetails.tsx
  src/pages/InvoiceOverview.tsx
  translations/base.json
Labels: 🛠 feature

#1953 fix: table thead row size
  src/components/designSystem/Table/Table.tsx
Labels: 🎨 UI

#1955 refactor: extract customer information
  src/components/customers/addDrawer/AddCustomerDrawer.tsx
  src/components/customers/addDrawer/CustomerInformation.tsx
Labels: 🌈 improvement

#1956 misc: use Table component for billable metrics list
  src/components/billableMetrics/BillableMetricItem.tsx
  src/generated/graphql.tsx
  src/pages/BillableMetricsList.tsx
Labels: 🌈 improvement

#1957 bug: make sure table sticky action column is visible on scroll
  src/components/designSystem/Table/Table.tsx
Labels: 🐞 bug
