Repository getlago/lago-front, pull requests merged in 2025-08, with the labels that each got.

#2371 fix: infinite list fetch all items
  src/components/designSystem/InfiniteScroll.tsx
  src/components/settings/integrations/IntegrationItemLine.tsx
  src/pages/SubscriptionDetails.tsx
  src/pages/SubscriptionsPage.tsx
  src/pages/features/FeaturesList.tsx
Labels: 🐞 bug

#2378 misc: few spacing adjustments
  src/components/layouts/Settings.tsx
  src/pages/settings/BillingEntity/sections/BillingEntityMain.tsx
Labels: 🌈 improvement

#2382 deps: fix brace-expansion CVE
  package.json
  packages/configs/package.json
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2384 misc: handle copy for InvoiceRegenerated activity type
  src/components/activityLogs/utils.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement

#2400 fix: warning filters
  src/components/designSystem/Filters/ActiveFiltersList.tsx
  src/components/form/ComboBox/ComboBoxVirtualizedList.tsx
Labels: 🐞 bug

#2390 feat: define boundaries on one-off fees
  src/components/invoices/EditFeeBillingPeriod.tsx
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/core/constants/form.ts
  src/core/formats/__tests__/formatInvoiceItemsMap.test.ts
  src/core/formats/formatInvoiceItemsMap.ts
  src/core/utils/invoiceUtils.ts
  src/generated/graphql.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CustomerInvoiceDetails.tsx
  src/pages/CustomerInvoiceRegenerate.tsx
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend

#2395 feat: filter customers by active subscriptions
  src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/filtersElements/FiltersItemActiveSubscriptions.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemAmount.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/utils.ts
  src/generated/graphql.tsx
  src/pages/CustomersList.tsx
  translations/base.json
Labels: 🛠 feature

#2404 misc: make subscription actions tooltip more generic
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/pages/SubscriptionsPage.tsx
  translations/base.json
Labels: 🌈 improvement

#2415 fix: remove fixed width
  src/components/designSystem/Table/ChargeTable.tsx
Labels: 🐞 bug, 🎨 UI

#2424 misc: add missing translation
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nb.json
  translations/sv.json
Labels: 🥷 chore
