Repository getlago/lago-front, pull requests merged in 2025-07, with the labels that each got.

#2289 feat: display pricing units in invoice details
  src/components/invoices/details/EditFeeDrawer.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduated.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePackage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLineVolume.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🛠 feature

#2294 bug: update email validation
  src/formValidation/__tests__/initializeYup.test.ts
  src/formValidation/initializeYup.ts
  src/formValidation/schema.d.ts
  src/pages/CreateCustomer.tsx
  src/pages/CustomerRequestOverduePayment/__tests__/validateEmails.test.ts
  src/pages/CustomerRequestOverduePayment/index.tsx
  src/pages/CustomerRequestOverduePayment/validateEmails.ts
Labels: 🐞 bug

#2299 refactor(design-system): 🔨 add more accessibility to tooltip
  packages/design-system/src/components/Tooltip.tsx
Labels: 🌈 improvement

#2301 bug: prevent skeleton to overflow
  packages/design-system/src/components/Skeleton.tsx
  src/components/designSystem/Skeleton.tsx
Labels: 🐞 bug

#2300 deps: bump @nangohq/frontend
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2305 misc: adjust recent copy addition
  translations/base.json
Labels: 🌈 improvement

#2307 fix: some warnings on runtime
  nginx/nginx.conf
  src/core/apolloClient/cache.ts
Labels: 🌈 improvement

#2313 bug: prevent double scroll in wallet topup page
  src/pages/wallet/CreateWalletTopUp.tsx
Labels: 🐞 bug

#2321 misc: display coupon code in customer coupon list
  src/components/customers/overview/CustomerCoupons.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement

#2323 bug: fixing missed combobox invocation updates
  src/components/coupons/AddBillableMetricToCouponDialog.tsx
  src/components/coupons/AddPlanToCouponDialog.tsx
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/components/customers/createCustomer/ExternalAppsAccordion/ExternalAppsAccordionLayout.tsx
  src/components/form/ComboBox/ComboBoxItem.tsx
  src/components/form/ComboBox/ComboBoxItemWrapper.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxItemWrapper.tsx
  src/pages/AlertForm.tsx
  src/pages/CreateBillableMetric.tsx
Labels: 🐞 bug

#2327 misc: better nav loading skeleton
  src/components/designSystem/VerticalMenu.tsx
Labels: 🌈 improvement

#2329 misc: adjust settings copy size
  src/pages/settings/BillingEntity/sections/BillingEntityMain.tsx
Labels: 🌈 improvement

#2314 feat: new payment list page
  packages/design-system/src/icons/coin-dollar.svg
  src/components/customers/CustomerPaymentsList.tsx
  src/components/customers/CustomerPaymentsTab.tsx
  src/components/invoices/InvoicePaymentList.tsx
  src/components/invoices/PaymentsList.tsx
  src/core/constants/tabsOptions.ts
  src/core/router/ObjectsRoutes.tsx
  src/generated/graphql.tsx
  src/layouts/MainNavLayout.tsx
  src/pages/CreatePayment.tsx
  src/pages/InvoicesPage.tsx
  src/pages/PaymentDetails.tsx
  src/pages/PaymentsPage.tsx
Labels: 👀 QA

#2331 misc: spin the reload icon on data fetch
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
Labels: 🌈 improvement

#2335 deps: bump lago-expression
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2334 deps: migrate cypress to latest v14
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2339 deps: get last lago-expression version
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2342 misc: align action with label baseline
  src/components/layouts/Section.tsx
  src/components/layouts/Settings.tsx
  src/components/settings/integrations/AnrokIntegrationSettings.tsx
  src/components/settings/integrations/AvalaraIntegrationSettings.tsx
Labels: 🌈 improvement

#2343 misc: make CMD + click redirects to the package component
  packages/design-system/tsconfig.build.json
Labels: 🥷 chore

#2348 deps: removed unused styled-engine package
  package.json
  packages/design-system/package.json
  packages/design-system/vite.config.ts
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2350 misc: display PU name in plan details
  src/components/plans/details/PlanDetailsChargesSection.tsx
  src/generated/graphql.tsx
  src/pages/CreatePlan.tsx
Labels: 🌈 improvement

#2349 fix: avoid rendering empty section on navigation
  src/layouts/MainNavLayout.tsx
Labels: 🐞 bug

#2354 feat: sso-enforcement
  cypress/e2e/00-auth/t10-login.cy.ts
  src/components/auth/GoogleAuthButton.tsx
  src/components/settings/authentication/AddOktaDialog.tsx
  src/core/apolloClient/cacheUtils.ts
  src/core/apolloClient/graphqlResolvers.tsx
  src/core/apolloClient/init.ts
  src/core/apolloClient/reactiveVars/authTokenVar.ts
  src/core/constants/authenticationMethodsMapping.ts
  src/core/router/SettingRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/useOrganizationInfos.ts
  src/hooks/usePermissions.ts
  src/layouts/MainNavLayout.tsx
  src/layouts/SettingsNavLayout.tsx
  src/pages/Invitation.tsx
  src/pages/auth/GoogleAuthCallback.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/LoginOkta.tsx
  src/pages/auth/OktaAuthCallback.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/SignUp.tsx
  src/pages/settings/Authentication/Authentication.tsx
  src/pages/settings/Authentication/OktaAuthenticationDetails.tsx
  src/pages/settings/Authentication/UpdateLoginMethodDialog.tsx
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend

#2359 fix: remove rule to delete member
  src/pages/settings/Members.tsx
Labels: 🐞 bug

#2357 feat: add billable metric limitation on wallet
  src/core/constants/form.ts
  src/generated/graphql.tsx
  src/pages/wallet/CreateWallet.tsx
  src/pages/wallet/components/ScopeSection.tsx
  src/pages/wallet/components/SettingsSection.tsx
  src/pages/wallet/types.ts
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend

#2352 feat: CRUD for feature entitlement
  packages/design-system/src/lib/muiTheme.ts
  src/components/SearchInput.tsx
  src/components/features/DeleteFeatureDialog.tsx
  src/components/features/FeatureDetailsOverview.tsx
  src/components/features/FeaturePrivilegeAccordion.tsx
  src/core/apolloClient/cache.ts
  src/core/apolloClient/graphqlResolvers.tsx
  src/core/constants/form.ts
  src/core/constants/tabsOptions.ts
  src/core/router/ObjectsRoutes.tsx
  src/core/utils/__tests__/domUtils.test.tsx
  src/core/utils/domUtils.ts
  src/core/utils/featureFlags.ts
  src/generated/graphql.tsx
  src/hooks/usePermissions.ts
  src/layouts/MainNavLayout.tsx
  src/pages/features/FeatureDetails.tsx
  src/pages/features/FeatureForm.tsx
  src/pages/features/FeaturesList.tsx
  src/pages/features/__tests__/utils.test.ts
  src/pages/features/utils.ts
  src/styles/muiTheme.ts
  translations/base.json
Labels: 🛠 feature

#2361 misc: allow to download payment link from UI
  src/components/customers/CustomerInvoicesList.tsx
  src/components/invoices/InvoicesList.tsx
  src/generated/graphql.tsx
  src/hooks/usePermissionsInvoiceActions.ts
  src/pages/CustomerInvoiceDetails.tsx
  translations/base.json
Labels: 🌈 improvement, ⛔️ Need Backend

#2366 bug: added .dockerignore file
  .dockerignore
  Dockerfile
Labels: 🌈 improvement

#2367 bug: make sure expected not found error don't raise alert
  src/pages/CustomerInvoiceDetails.tsx
Labels: 🐞 bug

#2369 misc: add beta chip on feature pages
  src/pages/features/FeatureForm.tsx
  src/pages/features/FeaturesList.tsx
  src/styles/designSystem/PageHeader.tsx
Labels: 🌈 improvement

#2370 deps: bump @nangohq/frontend
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2372 misc: improve the customer invoice loading experience
  src/components/customers/CustomerInvoicesList.tsx
  src/components/customers/CustomerInvoicesTab.tsx
Labels: 🌈 improvement

#2373 misc: unify subscriptions list typos
  src/components/TimezoneDate.tsx
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/pages/SubscriptionsPage.tsx
Labels: 🌈 improvement
