Repository getlago/lago-front, pull requests merged in 2025-09, with the labels that each got.

#2429 bug: email preview header wrong height
  src/pages/settings/BillingEntity/sections/BillingEntityEmailScenariosConfig.tsx
Labels: 🐞 bug

#2431 bug: rename portuguese-brasil locale code
  src/components/customers/CustomerSettings.tsx
  src/components/customers/EditCustomerDocumentLocaleDialog.tsx
  src/components/settings/LanguageSettingsButton.tsx
  src/components/settings/invoices/EditBillingEntityDocumentLocaleDialog.tsx
  src/core/translations/documentLocales.ts
  src/core/translations/types.ts
  src/pages/settings/BillingEntity/sections/BillingEntityInvoiceSettings.tsx
  translations/pt-BR.json
Labels: 🐞 bug

#2442 bug: define default dateTo on some logs queries
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/filtersElements/FiltersItemLoggedDate.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/useFilters.ts
  src/components/designSystem/Filters/utils.ts
  src/components/developers/activityLogs/ActivityLogs.tsx
  src/components/developers/apiLogs/ApiLogs.tsx
Labels: 🐞 bug

#2443 feat(ai agent): update design system
  packages/configs/tailwind.config.ts
  packages/design-system/playground/components/IconsSection.tsx
  packages/design-system/src/components/AiBadge.tsx
  packages/design-system/src/components/Icon/mapping.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/icons/sparkles-base.svg
Labels: 🌈 improvement

#2446 misc: add missing Italian translations
  translations/it.json
Labels: 🥷 chore

#2445 feat(ai-agent): introduce new ai agent context
  src/App.tsx
  src/hooks/aiAgent/aiAgentReducer.ts
  src/hooks/aiAgent/useAiAgent.tsx
Labels: 🛠 feature

#2450 misc: remove "selected" logic on invoice custom section
  src/components/customers/CustomerSettings.tsx
  src/components/customers/EditCustomerInvoiceCustomSectionsDialog.tsx
  src/components/settings/invoices/AddBillingEntityVatRateDialog.tsx
  src/components/settings/invoices/DefaultCustomSectionDialog.tsx
  src/components/settings/invoices/DeleteBillingEntityVatRateDialog.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditInvoiceCustomSection.ts
  src/pages/settings/BillingEntity/sections/BillingEntityInvoiceSettings.tsx
  src/pages/settings/Invoices/CreateCustomSection.tsx
  translations/base.json
  translations/pt-BR.json
Labels: 🌈 improvement

#2453 misc(creditNotes): validate form has at least one fee checked
  src/components/creditNote/__tests__/utils.test.ts
  src/components/creditNote/utils.ts
  src/pages/CreateCreditNote.tsx
Labels: 🐞 bug

#2454 bug: always hide entitlements on subscription details overview
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
  src/components/plans/details/PlanDetailsOverview.tsx
  src/components/subscriptions/SubscriptionDetailsOverview.tsx
Labels: 🐞 bug

#2457 deps: bumb nangohq to fix a high severity CVE on axios
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2461 bug: restore the canDispute action
  src/hooks/__tests__/usePermissionsInvoiceActions.test.ts
  src/hooks/usePermissionsInvoiceActions.ts
Labels: 🐞 bug

#2462 misc: make invoice related permissions relies on the same logic
  src/components/invoices/InvoicesList.tsx
  src/hooks/__tests__/usePermissionsInvoiceActions.test.ts
  src/hooks/usePermissionsInvoiceActions.ts
  src/pages/CustomerInvoiceDetails.tsx
Labels: 🌈 improvement

#2464 deps: bump cypress version to latest
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2463 feat(invoice): display wallet or transaction name on fee line
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/generated/graphql.tsx
Labels: 🛠 feature

#2468 misc: rename usage charge related elements
  src/components/plans/CommitmentsSection.tsx
  src/components/plans/UsageChargeAccordion.tsx
  src/components/plans/UsageChargesSection.tsx
  src/components/plans/__tests__/UsageChargeAccordion.test.tsx
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
  src/components/plans/details/PlanDetailsChargesSection.tsx
  src/components/plans/types.ts
  src/generated/graphql.tsx
  src/pages/CreatePlan.tsx
  src/pages/subscriptions/CreateSubscription.tsx
Labels: 🥷 chore

#2475 bug: fix date format tests
  src/core/timezone/__tests__/utils.test.ts
  src/core/timezone/config.ts
  src/core/timezone/utils.ts
  src/generated/graphql.tsx
Labels: 🐞 bug, 🥷 chore
