Repository getlago/lago-front, pull requests merged in 2025-05, with the labels that each got.

#2159 misc: clear LS last visited route before goBack on home
  src/hooks/core/useLocationHistory.ts
  src/layouts/Settings.tsx
Labels: 🐞 bug

#2161 deps: unify vite version accros packages
  package.json
  packages/design-system/package.json
  packages/design-system/vite.config.ts
  pnpm-lock.yaml
Labels: 🥷 chore, 🔗 dependencies

#2162 misc: migrate come components to TW
  src/layouts/Settings.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🌈 improvement

#2164 misc: Some TW migration and template adjustments
  src/components/form/Radio/RadioGroupField.tsx
  src/components/graphs/Gross.tsx
  src/components/graphs/Invoices.tsx
  src/components/graphs/Mrr.tsx
  src/components/graphs/Overview.tsx
  src/components/graphs/Usage.tsx
  src/components/invoices/EditInvoiceItemDescriptionDialog.tsx
  src/components/invoices/EditInvoiceItemTaxDialog.tsx
  src/components/invoices/InvoiceCreditNoteList.tsx
  src/components/plans/ChargeFilter.tsx
  src/components/wallets/VoidWalletDialog.tsx
  src/hooks/plans/useChargeForm.tsx
Labels: 🌈 improvement

#2165 misc: display dash if no sub startedAt
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/generated/graphql.tsx
Labels: 🐞 bug

#2166 bug: prevent sub display if parent is terminated
  src/components/customers/overview/CustomerSubscriptionsList.tsx
Labels: 🐞 bug

#2167 bug: allow to reset invoice display name value
  src/components/invoices/EditInvoiceDisplayName.tsx
Labels: 🐞 bug

#2168 misc: migrate some plan component to TW and fix warnings
  packages/configs/tailwind.config.ts
  src/components/plans/ChargeBillingRadioGroup.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/ChargesSection.tsx
  src/components/plans/CommitmentsSection.tsx
  src/components/plans/CustomCharge.tsx
  src/components/plans/DynamicCharge.tsx
  src/components/plans/FixedFeeSection.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/GraduatedPercentageChargeTable.tsx
  src/components/plans/PackageCharge.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/components/plans/ProgressiveBillingSection.tsx
  src/components/plans/StandardCharge.tsx
  src/components/plans/VolumeChargeTable.tsx
Labels: 🌈 improvement

#2170 misc: show subscription table on loading
  src/components/customers/overview/CustomerSubscriptionsList.tsx
Labels: 🌈 improvement

#2178 deps: fix some babel deps to fix CVE
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2176 misc: allow to re-connect a Xero connection from settings
  src/generated/graphql.tsx
  src/pages/settings/XeroIntegrationDetails.tsx
  translations/base.json
Labels: 🌈 improvement

#2175 bug: better invoice graph loading
  src/components/graphs/Invoices.tsx
Labels: 🐞 bug

#2190 misc: migrate some styled components to tailwind
  .vscode/lago.code-snippets
  packages/configs/tailwind.config.ts
  src/components/invoices/InvoiceCustomerInfos.tsx
  src/components/invoices/Metadatas.tsx
  src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
  src/components/invoices/details/InvoiceDetailsTableFooter.tsx
  src/pages/CustomerDraftInvoicesList.tsx
  src/pages/CustomerInvoiceDetails.tsx
  src/pages/InvoiceOverview.tsx
Labels: 🌈 improvement

#2191 bug: use new attributes for subscription
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/components/subscriptions/SubscriptionInformations.tsx
  src/generated/graphql.tsx
Labels: 🐞 bug

#2193 bug: add missing permissions in API key form
  src/core/apolloClient/graphqlResolvers.tsx
  src/generated/graphql.tsx
  src/pages/developers/ApiKeysForm.tsx
  translations/base.json
Labels: 🐞 bug

#2194 misc: use TW in charge components
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargeOptionsAccordion.tsx
Labels: 🌈 improvement

#2196 bug: make sure to check on array lenght as boolean
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
Labels: 🐞 bug

#2195 misc: mainObjectForm to use TW
  packages/configs/tailwind.config.ts
  src/components/customers/AddCouponToCustomerDialog.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreateCreditNote.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreatePlan.tsx
  src/pages/CreateTax.tsx
  src/styles/mainObjectsForm.tsx
Labels: 🌈 improvement

#2199 misc: unify tax error translations
  src/pages/CustomerInvoiceDetails.tsx
  translations/base.json
Labels: 🌈 improvement

#2198 misc: move alert tag to enter the correct spacing parent
  src/pages/CreateInvoice.tsx
Labels: 🌈 improvement

#2201 bug: use correct padding on mainObjectForm Main conponent
  src/styles/mainObjectsForm.tsx
Labels: 🐞 bug

#2205 fix: update layout due to multiple scrollbars
  src/layouts/SideNavLayout.tsx
  src/pages/AddOnsList.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CouponsList.tsx
  src/pages/CustomersList.tsx
  src/pages/PlansList.tsx
Labels: 🌈 improvement

#2207 chore: remove duplicated copy keys
  translations/base.json
Labels: 🥷 chore

#2177 feat: Add alert tab and part of the form
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/components/subscriptions/SubscriptionAlertsList.tsx
  src/components/subscriptions/alerts/DeleteAlertDialog.tsx
  src/core/constants/tabsOptions.ts
  src/core/router/ObjectsRoutes.tsx
  src/core/utils/featureFlags.ts
  src/generated/graphql.tsx
  src/pages/AlertForm.tsx
  src/pages/SubscriptionDetails.tsx
  translations/base.json
Labels: 🛠 feature

#2200 feat: new developer console
  package.json
  packages/configs/tailwind.config.ts
  packages/design-system/src/components/Tooltip.tsx
  pnpm-lock.yaml
  src/App.tsx
  src/components/CodeSnippet/CodeSnippet.tsx
  src/components/CodeSnippet/codeSnippet.css
  src/components/RouteWrapper.tsx
  src/components/TimezoneDate.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/designSystem/Tooltip.tsx
  src/components/developers/DebuggerEventDetails.tsx
  src/components/developers/DevtoolsRouter.tsx
  src/components/developers/DevtoolsView.tsx
  src/components/developers/EventItem.tsx
  src/components/developers/LogsLayout.tsx
  src/components/developers/WebhookLogDetails.tsx
  src/components/developers/WebhookLogItem.tsx
  src/components/developers/apiKeys/ApiKeys.tsx
  src/components/developers/apiKeys/DeleteApiKeyDialog.tsx
  src/components/developers/apiKeys/RotateApiKeyDialog.tsx
  src/components/developers/events/EventDetails.tsx
  src/components/developers/events/EventTable.tsx
  src/components/developers/events/Events.tsx
  src/components/developers/views.ts
  src/components/developers/webhooks/CreateWebhookDialog.tsx
  src/components/developers/webhooks/DeleteWebhookDialog.tsx
  src/components/developers/webhooks/WebhookLogDetails.tsx
  src/components/developers/webhooks/WebhookLogTable.tsx
  src/components/developers/webhooks/WebhookLogs.tsx
  src/components/developers/webhooks/Webhooks.tsx
  src/components/layouts/CenteredPage.tsx
  src/core/apolloClient/cache.ts
  src/core/apolloClient/cacheUtils.ts
  src/core/constants/statusWebhookMapping.ts
  src/core/router/DevelopperRoutes.tsx
  src/core/router/index.tsx
  src/core/utils/getCurrentBreakpoint.ts
  src/generated/graphql.tsx
  src/hooks/core/useLocationHistory.ts
  src/hooks/useDeveloperTool.tsx
  src/layouts/Developers.tsx
  src/layouts/SideNavLayout.tsx
  src/pages/auth/Login.tsx
  src/pages/developers/ApiKeysForm.tsx
  src/pages/developers/Debugger.tsx
  src/pages/developers/WebhookLogs.tsx
  src/pages/developers/Webhooks.tsx
  translations/base.json
Labels: 🛠 feature

#2211 fix: select first event on refetch
  src/components/developers/events/Events.tsx
  src/components/developers/webhooks/WebhookLogs.tsx
Labels: 🐞 bug

#2215 bug(customerPortal): prevent unexpected calls to be triggered
  src/pages/auth/PortalInit.tsx
Labels: 🐞 bug

#2216 bug(coupons): expirationAt should be set at end of day
  src/core/utils/__tests__/dateUtils.test.ts
  src/core/utils/dateUtils.ts
  src/pages/CreateCoupon.tsx
Labels: 🐞 bug

#2218 fix(console): set active row
  src/components/developers/events/EventTable.tsx
  src/components/developers/events/Events.tsx
  src/components/developers/webhooks/WebhookLogs.tsx
Labels: 🐞 bug

#2220 feat: new activity logs components
  src/components/activityLogs/ActivityLogsTable.tsx
  src/components/activityLogs/utils.ts
  src/components/designSystem/Table/Table.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🛠 feature

#2226 misc: unify finalised and draft customer invoice list
  src/components/customers/CustomerInvoicesList.tsx
  src/components/customers/CustomerInvoicesTab.tsx
Labels: 🌈 improvement

#2225 feat: new billable metric details page
  cypress/e2e/10-resources/t30-create-bm.cy.ts
  src/components/billableMetrics/BillableMetricDetailsOverview.tsx
  src/core/constants/tabsOptions.ts
  src/core/formats/formatBillableMetricsItems.ts
  src/core/router/ObjectsRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/useCreateEditBillableMetric.ts
  src/pages/BillableMetricDetails.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CreateBillableMetric.tsx
  translations/base.json
Labels: 🛠 feature, 👀 QA

#2228 misc: redirect to invoice details after creation
  src/pages/CreateInvoice.tsx
Labels: 🌈 improvement

#2206 feat: release avalara integration feature
  src/components/settings/integrations/AvalaraIntegrationMapItemDialog.tsx
  src/core/apolloClient/graphqlResolvers.tsx
  src/core/constants/externalUrls.ts
  src/core/utils/featureFlags.ts
  src/generated/graphql.tsx
  src/main.css
  src/pages/CreateInvoice.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerInvoiceDetails.tsx
  src/pages/InvoiceOverview.tsx
  src/pages/settings/Integrations.tsx
  translations/base.json
Labels: 🛠 feature, 🌈 improvement, ⛔️ Need Backend
