Repository getlago/lago-front, pull requests merged in 2025-02, with the labels that each got.

#2010 misc: add new HorizontalDataTable
  package.json
  src/components/designSystem/Table/HorizontalDataTable.tsx
  src/components/designSystem/Table/index.ts
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/__devOnly/fixtures.ts
  tailwind.config.ts
  yarn.lock
Labels: 🛠 feature

#2012 bug: add fee only available on draft invoices
  src/components/invoices/details/InvoiceDetailsTable.tsx
Labels: 🐞 bug

#2013 misc: remove feature flag for boleto
  src/components/customers/createCustomer/ExternalAppsAccordion/PaymentProvidersAccordion.tsx
  src/core/utils/featureFlags.ts
Labels: 🌈 improvement

#2015 misc: change webhook limit to 10
  src/pages/developers/Webhooks.tsx
Labels: 🌈 improvement

#2021 chore: unify imports and remove unused NavigationEnum
  src/components/customers/CustomerInvoicesList.tsx
  src/components/invoices/InvoicesList.tsx
  src/core/constants/NavigationEnum.ts
  src/pages/CreateCreditNote.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerInvoiceDetails.tsx
Labels: 🥷 chore

#2022 bug: prevent fee creation for some flagged subscriptions
  src/components/invoices/details/InvoiceDetailsTable.tsx
  src/core/formats/formatInvoiceItemsMap.ts
  src/generated/graphql.tsx
Labels: 🐞 bug

#2023 misc(new-analytics): add page and route structure
  src/core/constants/tabsOptions.ts
  src/core/router/index.tsx
  src/generated/graphql.tsx
  src/pages/analytics/Invoices.tsx
  src/pages/analytics/Mrr.tsx
  src/pages/analytics/NewAnalytics.tsx
  src/pages/analytics/PrepaidCredits.tsx
  src/pages/analytics/RevenueStreams.tsx
  src/pages/analytics/Usage.tsx
  translations/base.json
Labels: 🛠 feature

#2024 chore: rename horizontalDataTable column props into rows
  src/components/designSystem/Table/HorizontalDataTable.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🥷 chore

#2025 misc: HorizontalDataTable can interact with given data index state
  src/components/designSystem/Table/HorizontalDataTable.tsx
Labels: 🌈 improvement

#2027 fix: handle not found error for lifetime usage
  src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx
  translations/base.json
Labels: 🐞 bug

#2029 fix: add location when search params changes to history
  src/components/RouteWrapper.tsx
  src/core/apolloClient/reactiveVars/locationHistoryVar.ts
Labels: 🐞 bug

#2034 refactor: replace react-window usage for tanstack/virtual
  package.json
  src/components/customers/__tests__/EditCustomerVatRateDialog.test.tsx
  src/components/designSystem/__tests__/ButtonLink.test.tsx
  src/components/form/ComboBox/ComboBoxVirtualizedList.tsx
  src/components/form/ComboBox/ComboboxList.tsx
  src/components/form/MultipleComboBox/MultipleComboBoxVirtualizedList.tsx
  yarn.lock
Labels: 🌈 improvement

#2036 misc: adjust HorizontalDataTable behaviors
  src/components/designSystem/Table/HorizontalDataTable.tsx
Labels: 🌈 improvement

#2035 misc: add new MultipleLineChart component
  src/components/designSystem/graphs/MultipleLineChart.tsx
  src/components/designSystem/graphs/const.tsx
  src/components/designSystem/graphs/fixtures.ts
Labels: 🌈 improvement

#2038 fix: compare numbers with same precision
  src/components/creditNote/CreditNoteFormCalculation.tsx
Labels: 🐞 bug

#2040 secu: fix CVE #93
  package.json
  yarn.lock
Labels: 🔗 dependencies

#2041 fix: remove usage of Date api in favour of DateTime
  src/components/billableMetrics/CustomExpressionDrawer.tsx
  src/components/designSystem/Filters/utils.ts
  src/components/wallets/WalletAccordion.tsx
  src/components/wallets/WalletTransactionListItem/__tests__/index.test.tsx
  src/core/timezone/utils.ts
Labels: 🐞 bug

#2042 misc: few improvement for new analytics
  package.json
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/designSystem/graphs/MultipleLineChart.tsx
  src/generated/graphql.tsx
  yarn.lock
Labels: 🌈 improvement

#2037 feat: add support for stripe bank transfers
  src/components/customers/CustomerMainInfos.tsx
  src/components/customers/createCustomer/ExternalAppsAccordion/PaymentProvidersAccordion.tsx
  src/components/designSystem/Status.tsx
  src/core/constants/statusInvoiceMapping.ts
  src/generated/graphql.tsx
  translations/base.json
Labels: 🛠 feature

#2043 fix: pending invoices details page + filters
  src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx
  src/components/invoices/details/InvoiceDetailsTableFooter.tsx
Labels: 🐞 bug

#2044 misc: fix typo
  translations/base.json
Labels: 🥷 chore

#2047 bug: display applied filters if they contain a prefix
  src/components/designSystem/Filters/ActiveFiltersList.tsx
  src/components/designSystem/Filters/useFilters.ts
Labels: 🐞 bug

#2048 feat: Revenue streams improvements
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx
  src/components/designSystem/Filters/QuickFilters.tsx
  src/components/designSystem/Filters/TimeGranularitySelector.tsx
  src/components/designSystem/Filters/__tests__/useFilters.test.tsx
  src/components/designSystem/Filters/context.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/useFilters.ts
  src/components/designSystem/Filters/utils.ts
  src/components/designSystem/Icon/mapping.tsx
  src/components/invoices/InvoicesList.tsx
  src/core/constants/filters.ts
  src/pages/CustomersList.tsx
  src/public/icons/arrow-down-circle-filled.svg
  src/public/icons/arrow-up-circle-filled.svg
  translations/base.json
Labels: 🛠 feature

#2049 fix: extra padding on menu popper in side nav
  src/layouts/SideNavLayout.tsx
  src/styles/designSystem/MenuPopper.tsx
  tailwind.config.ts
Labels: 🎨 UI
