Repository getlago/lago-front, pull requests merged in 2025-06, with the labels that each got.

#2230 fix: prevent active queries
  src/core/apolloClient/cacheUtils.ts
Labels: 🐞 bug

#2229 fix: format issues and Activity Log improvements
  src/components/activityLogs/utils.ts
  src/components/developers/activityLogs/ActivityLogDetails.tsx
  src/components/developers/activityLogs/ActivityLogs.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🌈 improvement

#2232 bug(ApiKeysForm): prevent checkbox's focus ring crop
  src/pages/developers/ApiKeysForm.tsx
Labels: 🐞 bug

#2236 bug: prevent redirection route to be in history
  src/pages/settings/SettingsHomePage.tsx
Labels: 🐞 bug

#2239 misc: remove some styled components
  src/components/designSystem/Table/Table.tsx
  src/pages/settings/AdyenIntegrationDetails.tsx
  src/pages/settings/AdyenIntegrations.tsx
  src/pages/settings/AnrokIntegrations.tsx
  src/pages/settings/AvalaraIntegrations.tsx
  src/pages/settings/CashfreeIntegrations.tsx
  src/pages/settings/GocardlessIntegrationDetails.tsx
  src/pages/settings/GocardlessIntegrations.tsx
  src/pages/settings/HubspotIntegrations.tsx
  src/pages/settings/MoneyhashIntegrations.tsx
  src/pages/settings/NetsuiteIntegrations.tsx
  src/pages/settings/SalesforceIntegrations.tsx
  src/pages/settings/StripeIntegrationDetails.tsx
  src/pages/settings/StripeIntegrations.tsx
  src/pages/settings/XeroIntegrations.tsx
  src/styles/designSystem/List.tsx
  src/styles/designSystem/MenuPopper.tsx
  src/styles/designSystem/PopperComponents.tsx
  src/styles/designSystem/index.ts
Labels: 🌈 improvement

#2246 fix: remove payment tab for draft invoice
  src/pages/CustomerInvoiceDetails.tsx
Labels: 🐞 bug

#2249 bug(Avalara): catch auth error and display correct message
  src/components/settings/integrations/AddAvalaraDialog.tsx
  src/components/settings/integrations/AddHubspotDialog.tsx
  src/components/settings/integrations/AddNetsuiteDialog.tsx
  src/components/settings/integrations/AddSalesforceDialog.tsx
  src/components/settings/integrations/AddXeroDialog.tsx
  translations/base.json
Labels: 🐞 bug

#2247 feat(ActivityLogs): new page for each resource
  src/components/activityLogs/utils.ts
  src/components/billableMetrics/BillableMetricDetailsActivityLogs.tsx
  src/components/coupons/CouponDetailsActivityLogs.tsx
  src/components/creditNote/CreditNoteDetailsActivityLogs.tsx
  src/components/customers/CustomerActivityLogs.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemAmount.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemResourceTypes.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/utils.ts
  src/components/developers/DevtoolsView.tsx
  src/components/developers/activityLogs/ActivityLogDetails.tsx
  src/components/invoices/InvoiceActivityLogs.tsx
  src/components/plans/details/PlanDetailsActivityLogs.tsx
  src/components/subscriptions/SubscriptionActivityLogs.tsx
  src/components/wallets/WalletAccordion.tsx
  src/core/apolloClient/cache.ts
  src/core/constants/tabsOptions.ts
  src/generated/graphql.tsx
  src/hooks/useDeveloperTool.tsx
  src/pages/BillableMetricDetails.tsx
  src/pages/CouponDetails.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerDetails.tsx
  src/pages/CustomerInvoiceDetails.tsx
  src/pages/PlanDetails.tsx
  src/pages/SubscriptionDetails.tsx
  translations/base.json
Labels: 🛠 feature

#2252 fix: add permissions to fetch activity logs
  src/components/billableMetrics/BillableMetricDetailsActivityLogs.tsx
  src/components/coupons/CouponDetailsActivityLogs.tsx
  src/components/creditNote/CreditNoteDetailsActivityLogs.tsx
  src/components/customers/CustomerActivityLogs.tsx
  src/components/developers/DevtoolsRouter.tsx
  src/components/developers/DevtoolsView.tsx
  src/components/invoices/InvoiceActivityLogs.tsx
  src/components/plans/details/PlanDetailsActivityLogs.tsx
  src/components/subscriptions/SubscriptionActivityLogs.tsx
  src/components/wallets/WalletAccordion.tsx
  src/generated/graphql.tsx
  src/hooks/usePermissions.ts
  src/pages/BillableMetricDetails.tsx
  src/pages/CouponDetails.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerDetails.tsx
  src/pages/CustomerInvoiceDetails.tsx
  src/pages/PlanDetails.tsx
  src/pages/SubscriptionDetails.tsx
Labels: 🛠 feature

#2253 bug: fix usage graph loading
  src/components/graphs/Usage.tsx
Labels: 🐞 bug

#2254 bug: display alert if no access to feature
  src/pages/CustomerRequestOverduePayment/index.tsx
Labels: 🐞 bug

#2256 deps: unify versions in config package
  packages/configs/package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2258 misc: remove some linter warnings
  cypress/support/e2e.ts
  src/components/TimezoneDate.tsx
  src/components/coupons/DeleteCouponDialog.tsx
  src/components/designSystem/ButtonLink.tsx
  src/components/designSystem/Toasts/ToastContainer.tsx
  src/components/designSystem/graphs/StackedBarChart.tsx
  src/components/form/AmountInput/AmountInput.tsx
  src/components/form/ComboBox/ComboBox.tsx
  src/components/form/DatePicker/DatePicker.tsx
  src/components/form/MultipleComboBox/MultipleComboBox.tsx
  src/components/plans/ChargePercentage.tsx
  src/core/formats/__tests__/formatCreditNotesItems.test.ts
  src/pages/CreateBillableMetric.tsx
  src/pages/CreateTax.tsx
Labels: 🌈 improvement

#2263 fix: use invoiceId on url params
  src/components/activityLogs/utils.tsx
  src/components/developers/activityLogs/ActivityLogDetails.tsx
  src/generated/graphql.tsx
Labels: 🐞 bug

#2265 bug: make sure the button bar takes full width
  src/pages/CreatePlan.tsx
Labels: 🐞 bug

#2259 misc: allow to set pricingGroupKeys on any type of charge except custom
  src/components/plans/ChargePercentage.tsx
  src/components/plans/DynamicCharge.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/GraduatedPercentageChargeTable.tsx
  src/components/plans/PackageCharge.tsx
  src/components/plans/PricingGroupKeys.tsx
  src/components/plans/StandardCharge.tsx
  src/components/plans/VolumeChargeTable.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/core/constants/form.ts
  src/core/serializers/serializePlanInput.ts
  src/hooks/plans/useGraduatedChargeForm.ts
  translations/base.json
Labels: 🛠 feature

#2257 misc: rename groupedBy attribute in plan form
  src/components/plans/ChargeAccordion.tsx
  src/components/plans/ChargePercentage.tsx
  src/components/plans/ChargeWrapperSwitch.tsx
  src/components/plans/CustomCharge.tsx
  src/components/plans/DynamicCharge.tsx
  src/components/plans/GraduatedChargeTable.tsx
  src/components/plans/GraduatedPercentageChargeTable.tsx
  src/components/plans/PackageCharge.tsx
  src/components/plans/PricingGroupKeys.tsx
  src/components/plans/StandardCharge.tsx
  src/components/plans/VolumeChargeTable.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/components/plans/types.ts
  src/core/constants/form.ts
  src/core/serializers/__tests__/serializePlanInput.test.ts
  src/core/serializers/getPropertyShape.ts
  src/core/serializers/serializePlanInput.ts
  src/generated/graphql.tsx
  src/hooks/__tests__/fixtures.ts
  src/hooks/plans/useGraduatedChargeForm.ts
  src/hooks/plans/useGraduatedPercentageChargeForm.ts
  src/hooks/plans/useVolumeChargeForm.ts
  src/pages/CreatePlan.tsx
  translations/base.json
Labels: 🌈 improvement, ⛔️ Need Backend

#2272 fix: no hyperlinks for deleted activity type
  src/components/activityLogs/utils.tsx
  src/components/developers/activityLogs/ActivityLogDetails.tsx
Labels: 🐞 bug

#2271 misc: autofill code on name update in form
  cypress/e2e/10-resources/t10-create-taxes.cy.ts
  cypress/e2e/10-resources/t30-create-bm.cy.ts
  cypress/e2e/10-resources/t40-create-plan.cy.ts
  cypress/e2e/10-resources/t60-coupons-create-edit-apply.cy.ts
  cypress/e2e/10-resources/t70-addon-create-edit.cy.ts
  cypress/support/reusableConstants.ts
  src/components/form/TextInput/TextInput.tsx
  src/components/plans/PlanSettingsSection.tsx
  src/core/utils/__tests__/updateNameAndMaybeCode.test.tsx
  src/core/utils/updateNameAndMaybeCode.ts
  src/pages/AlertForm.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreateTax.tsx
  src/pages/settings/BillingEntity/sections/BillingEntityCreateEdit.tsx
  src/pages/settings/Dunnings/CreateDunning.tsx
  src/pages/settings/Invoices/CreateCustomSection.tsx
Labels: 🌈 improvement

#2276 deps: remove styled-components
  .vscode/extensions.json
  package.json
  packages/design-system/package.json
  packages/design-system/tsconfig.json
  packages/design-system/tsconfig.playground.json
  packages/design-system/vite.config.ts
  pnpm-lock.yaml
  tsconfig.json
  vite.config.ts
Labels: 🔗 dependencies

#2275 feat: allow to create custom pricing
  src/core/apolloClient/cache.ts
  src/core/router/SettingRoutes.tsx
  src/core/utils/featureFlags.ts
  src/generated/graphql.tsx
  src/hooks/usePermissions.ts
  src/layouts/Settings.tsx
  src/pages/settings/Invoices/CreateCustomSection.tsx
  src/pages/settings/Invoices/CreatePricingUnit.tsx
  src/pages/settings/Invoices/InvoiceSections.tsx
  translations/base.json
Labels: 🛠 feature

#2279 bug: make sure inputs are aligned when error is displayed
  src/pages/CreateAddOn.tsx
Labels: 🐞 bug

#2281 feat: API logs in developer console
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemHttpMethods.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemHttpStatuses.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemRequestPath.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/utils.ts
  src/components/designSystem/Status.tsx
  src/components/developers/DevtoolsRouter.tsx
  src/components/developers/apiLogs/ApiLogDetails.tsx
  src/components/developers/apiLogs/ApiLogs.tsx
  src/components/developers/apiLogs/ApiLogsTable.tsx
  src/components/developers/apiLogs/mapping.tsx
  src/components/developers/views.ts
  src/core/apolloClient/cache.ts
  src/core/constants/filters.ts
  src/generated/graphql.tsx
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend
