Repository getlago/lago-front, pull requests merged in 2025-01, with the labels that each got.

#1959 misc: allow click on menu active sidebar item
  src/layouts/SideNavLayout.tsx
Labels: 🌈 improvement

#1958 misc: use Table component for plan list
  cypress/e2e/10-resources/t40-create-plan.cy.ts
  cypress/e2e/10-resources/t50-edit-plan.cy.ts
  src/components/GenericPlaceholder.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/designSystem/__tests__/Table.test.tsx
  src/components/plans/PlanItem.tsx
  src/generated/graphql.tsx
  src/pages/PlansList.tsx
Labels: 🌈 improvement

#1960 misc: use Table component for AddOns list
  src/components/addOns/AddOnItem.tsx
  src/components/designSystem/Table/Table.tsx
  src/generated/graphql.tsx
  src/pages/AddOnsList.tsx
Labels: 🌈 improvement

#1961 refactor: external apps improvement
  src/components/customers/addDrawer/ExternalAppsAccordion.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion/AccountingProvidersAccordion.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion/CRMProvidersAccordion.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion/ExternalAppsAccordionLayout.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion/PaymentProvidersAccordion.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion/TaxProvidersAccordion.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion/index.tsx
  src/components/customers/addDrawer/ExternalAppsAccordion/utils.ts
  src/generated/graphql.tsx
  src/hooks/useCreateEditCustomer.ts
Labels: 🌈 improvement

#1962 misc: use Table component for Coupons list
  src/components/coupons/CouponItem.tsx
  src/generated/graphql.tsx
  src/pages/CouponsList.tsx
  src/styles/designSystem/List.tsx
Labels: 🌈 improvement

#1963 misc(OneOffInvoice): allow 3 decimal value for units
  cypress/e2e/t30-create-one-off-invoice.cy.ts
  src/pages/CreateInvoice.tsx
Labels: 🌈 improvement

#1965 misc: some more styled component migration to TW
  src/components/PremiumWarningDialog.tsx
  src/components/customers/CustomerMainInfos.tsx
  src/components/developers/WebhookLogDetails.tsx
  src/components/plans/CommitmentsSection.tsx
  src/components/plans/ProgressiveBillingSection.tsx
  src/components/plans/details/PlanSubscriptionList.tsx
  src/components/settings/emails/UpdateOrganizationLogoDialog.tsx
  src/pages/AddOnDetails.tsx
  src/pages/CouponDetails.tsx
  src/pages/settings/AdyenIntegrationDetails.tsx
  src/pages/settings/GocardlessIntegrationDetails.tsx
  src/pages/settings/StripeIntegrationDetails.tsx
  src/styles/detailsPage.tsx
  tailwind.config.ts
Labels: 🌈 improvement

#1967 refactor: move CustomerInvoiceDetails into pages folder
  src/components/creditNote/utils.ts
  src/components/customers/CustomerInvoicesList.tsx
  src/components/invoices/InvoicesList.tsx
  src/core/constants/NavigationEnum.ts
  src/core/router/CustomerRoutes.tsx
  src/pages/CreateCreditNote.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerInvoiceDetails.tsx
  src/pages/InvoiceCreditNoteList.tsx
Labels: 🌈 improvement

#1969 misc: remove feature flag on salesforce integration display
  src/pages/settings/Integrations.tsx
Labels: 🛠 feature

#1970 misc(invoice-list-item): add issue a credit note action
  src/components/customers/CustomerInvoicesList.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/invoices/InvoicesList.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement

#1971 misc: align customersCount display in lists
  src/pages/AddOnsList.tsx
  src/pages/CouponsList.tsx
Labels: 🥷 chore

#1972 misc: restore list item icon
  src/pages/AddOnsList.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CouponsList.tsx
  src/pages/CustomersList.tsx
  src/pages/PlansList.tsx
Labels: 🌈 improvement

#1975 bug: make sure classname is merge with existing one
  src/styles/customer.tsx
  src/styles/mainObjectsForm.tsx
Labels: 🐞 bug

#1973 misc(Table): allow to open row link in new tab
  src/components/creditNote/CreditNotesTable.tsx
  src/components/customers/CustomerInvoicesList.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/designSystem/__tests__/Table.test.tsx
  src/components/invoices/InvoicesList.tsx
  src/pages/AddOnsList.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CouponsList.tsx
  src/pages/CustomersList.tsx
  src/pages/PlansList.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/developers/Webhooks.tsx
  src/pages/settings/EmailSettings.tsx
Labels: 🌈 improvement

#1977 bug(Combobox): fix element height with description
  src/components/form/ComboBox/ComboBoxVirtualizedList.tsx
Labels: 🐞 bug

#1978 misc: adjust some toast wordings
  src/components/customers/DeleteCustomerFinalizeZeroAmountInvoiceDialog.tsx
  translations/base.json
Labels: 🥷 chore, 🌈 improvement

#1981 fix(MultipleCombobox): regression chevron and clear icon wrong size
  src/components/form/MultipleComboBox/MultipleComboBox.tsx
Labels: 🐞 bug

#1982 bug(Volume charge): make sure amount calculation precision is correct
  package.json
  src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx
  src/hooks/plans/useVolumeChargeForm.ts
  yarn.lock
Labels: 🐞 bug

#1983 misc: switch from mathjs to decimaljs
  package.json
  src/hooks/plans/useVolumeChargeForm.ts
  yarn.lock
Labels: 🥷 chore

#1989 misc: slightly improve customer info perf
  src/components/customers/createCustomer/CustomerInformation.tsx
  src/pages/CreateCustomer.tsx
Labels: 🥷 chore

#1946 feat: invoice custom section
  src/components/customers/CustomerSettings.tsx
  src/components/customers/EditCustomerInvoiceCustomSectionsDialog.tsx
  src/components/settings/invoices/DefaultCustomSectionDialog.tsx
  src/components/settings/invoices/DeleteCustomSectionDialog.tsx
  src/components/settings/invoices/PreviewCustomSectionDrawer.tsx
  src/core/router/SettingRoutes.tsx
  src/generated/graphql.tsx
  src/hooks/usePermissions.ts
  src/pages/settings/Invoices/CreateCustomSection.tsx
  src/pages/settings/Invoices/InvoiceSettings.tsx
  translations/base.json
Labels: 🛠 feature

#1991 misc: improve confusing Okta setup copy
  translations/base.json
Labels: 🌈 improvement

#1992 misc: improve improved Okta setup copy
  translations/base.json
Labels: 🌈 improvement

#1990 feat: handle static filters and refactor component
  src/components/creditNote/CreditNotesTable.tsx
  src/components/designSystem/Filters/ActiveFiltersList.tsx
  src/components/designSystem/Filters/Filters.tsx
  src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx
  src/components/designSystem/Filters/FiltersPanelPopper.tsx
  src/components/designSystem/Filters/InvoiceStatusQuickFilter.tsx
  src/components/designSystem/Filters/QuickFilters.tsx
  src/components/designSystem/Filters/__tests__/useFilters.test.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/context.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemAmount.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemCreditNoteCreditStatus.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemCreditNoteReason.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemCreditNoteRefundStatus.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemCurrency.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemCustomer.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemInvoiceNumber.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemInvoiceType.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemIssuingDate.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentDisputeLost.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentOverdue.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx
  src/components/designSystem/Filters/index.ts
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/useFilters.ts
  src/components/designSystem/Filters/utils.ts
  src/components/designSystem/index.ts
  src/components/invoices/InvoicesList.tsx
  src/pages/InvoicesPage.tsx
Labels: 🌈 improvement

#1993 feat: add new partially filled icon
  src/components/designSystem/Icon/mapping.tsx
  src/public/icons/partially-filled.svg
Labels: 🌈 improvement

#1994 refactor: migrate PageHeader
  src/pages/AddOnDetails.tsx
  src/pages/AddOnsList.tsx
  src/pages/Analytics.tsx
  src/pages/BillableMetricsList.tsx
  src/pages/CouponDetails.tsx
  src/pages/CouponsList.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreateCreditNote.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreatePlan.tsx
  src/pages/CreateSubscription.tsx
  src/pages/CreateTax.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/CustomerDetails.tsx
  src/pages/CustomerDraftInvoicesList.tsx
  src/pages/CustomerInvoiceDetails.tsx
  src/pages/CustomerRequestOverduePayment/index.tsx
  src/pages/CustomersList.tsx
  src/pages/InvoicesPage.tsx
  src/pages/PlanDetails.tsx
  src/pages/PlansList.tsx
  src/pages/SubscriptionDetails.tsx
  src/pages/WalletForm/WalletForm.tsx
  src/pages/__devOnly/DesignSystem.tsx
  src/pages/developers/WebhookLogs.tsx
  src/pages/settings/AdyenIntegrationDetails.tsx
  src/pages/settings/AdyenIntegrations.tsx
  src/pages/settings/AnrokIntegrationDetails.tsx
  src/pages/settings/AnrokIntegrations.tsx
  src/pages/settings/Authentication/OktaAuthenticationDetails.tsx
  src/pages/settings/EmailScenarioConfig.tsx
  src/pages/settings/GocardlessIntegrationDetails.tsx
  src/pages/settings/GocardlessIntegrationOauthCallback.tsx
  src/pages/settings/GocardlessIntegrations.tsx
  src/pages/settings/HubspotIntegrationDetails.tsx
  src/pages/settings/HubspotIntegrations.tsx
  src/pages/settings/LagoTaxManagementIntegration.tsx
  src/pages/settings/NetsuiteIntegrationDetails.tsx
  src/pages/settings/NetsuiteIntegrations.tsx
  src/pages/settings/SalesforceIntegrationDetails.tsx
  src/pages/settings/SalesforceIntegrations.tsx
  src/pages/settings/StripeIntegrationDetails.tsx
  src/pages/settings/StripeIntegrations.tsx
  src/pages/settings/XeroIntegrationDetails.tsx
  src/pages/settings/XeroIntegrations.tsx
  src/styles/designSystem/PageHeader.tsx
Labels: 🌈 improvement

#1995 bug: update missed page header implementations
  src/pages/settings/CashfreeIntegrationDetails.tsx
  src/pages/settings/CashfreeIntegrations.tsx
Labels: 🐞 bug

#2000 chore: prevent dependabot auto merge
  renovate.json
Labels: 🥷 chore

#2002 misc: get last codegen
  src/generated/graphql.tsx
Labels: 🥷 chore
