Repository getlago/lago-front, pull requests merged in 2025-04, with the labels that each got.

#2101 misc(RevenueStreams): improve XAxis tick display logic
  src/components/analytics/revenueStreams/RevenueStreamsOverviewSection.tsx
  src/components/designSystem/graphs/MultipleLineChart.tsx
Labels: 🌈 improvement

#2102 feat: add refresh button on usage drawer
  src/components/customerPortal/usage/UsagePage.tsx
  src/components/customers/usage/SubscriptionUsageDetailDrawer.tsx
  src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
Labels: 🌈 improvement

#2103 misc: release analytics and improve navigation
  src/components/analytics/mrr/__tests__/utils.test.ts
  src/components/analytics/mrr/utils.ts
  src/components/designSystem/NavigationTab.tsx
  src/core/utils/featureFlags.ts
  src/pages/analytics/NewAnalytics.tsx
Labels: 🌈 improvement

#2104 bug(new-analytics): make sure dates are correctly handled
  src/components/analytics/mrr/useMrrAnalyticsOverview.ts
  src/components/analytics/revenueStreams/useRevenueAnalyticsOverview.ts
  src/components/designSystem/Filters/FiltersPanelPopper.tsx
  src/components/designSystem/Filters/__tests__/useFilters.test.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemDate.tsx
  src/components/designSystem/Filters/useFilters.ts
Labels: 🐞 bug

#2106 bug: no text should be wrapped in table rows
  src/components/analytics/mrr/MrrBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsCustomerBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsPlanBreakdownSection.tsx
Labels: 🐞 bug

#2108 misc: export dialog to use tailwind
  src/components/exports/ExportDialog.tsx
Labels: 🌈 improvement

#2107 refactor: details page migration
  src/components/SkeletonDetailsPage.tsx
  src/components/details/DetailsHeader.tsx
  src/components/details/DetailsJSONDisplay.tsx
  src/components/details/DetailsTableDisplay.tsx
  src/components/layouts/DetailsPage.tsx
  src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
  src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx
  src/components/plans/details/PlanDetailsChargesSection.tsx
  src/components/plans/details/PlanDetailsChargesSectionAccordion.tsx
  src/components/plans/details/PlanDetailsFixedFeeAccordion.tsx
  src/components/plans/details/PlanDetailsOverview.tsx
  src/components/plans/details/PlanSubscriptionList.tsx
  src/components/subscriptions/SubscriptionDetailsOverview.tsx
  src/components/subscriptions/SubscriptionInformations.tsx
  src/pages/AddOnDetails.tsx
  src/pages/CouponDetails.tsx
  src/pages/CreditNoteDetails.tsx
  src/pages/PlanDetails.tsx
  src/styles/detailsPage.tsx
Labels: 🌈 improvement

#2105 misc(CreditNoteTable): remove warnings and styled components
  src/components/creditNote/CreditNotesTable.tsx
Labels: 🌈 improvement

#2112 misc: improve our Sentry setup
  package.json
  src/components/ErrorBoundary.tsx
  src/core/apolloClient/init.ts
  src/main.tsx
  yarn.lock
Labels: 🌈 improvement

#2111 refactor: developers pages
  src/components/developers/CreateWebhookDialog.tsx
  src/components/developers/WebhookLogDetails.tsx
Labels: 🌈 improvement

#2116 chore(Sentry): enable replay sessions for errors
  src/main.tsx
Labels: 🥷 chore

#2117 chore(Sentry): record replay for 30% of errors
  src/main.tsx
Labels: 🥷 chore

#2119 fix: dates util function
  src/core/timezone/__tests__/utils.test.ts
  src/core/timezone/utils.ts
Labels: 🌈 improvement

#2113 fix(InvoiceCustomSection): rename applicable into configurable
  src/components/customers/CustomerSettings.tsx
  src/components/customers/EditCustomerInvoiceCustomSectionsDialog.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement, ⛔️ Need Backend

#2121 chore: migrate configs files into a specific package
  .github/workflows/codegen.yml
  .prettierignore
  .prettierrc
  .prettierrc.mjs
  eslint.config.mjs
  package.json
  packages/configs/.prettierrc.mjs
  packages/configs/eslint.config.mjs
  packages/configs/package.json
  packages/configs/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
Labels: 🌈 improvement

#2123 misc: fix credit note calculation loading state
  src/components/creditNote/CreditNoteEstimationLine.tsx
Labels: 🌈 improvement

#2126 chore: bump eslint
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: 🔗 dependencies

#2129 fix(issue-840): fetch customerId
  src/components/subscriptions/SubscriptionUsageTabContent.tsx
  src/generated/graphql.tsx
Labels: 🐞 bug

#2132 bug: prevent wrong copy displayed for invoice sync
  src/components/settings/integrations/AnrokIntegrationSettings.tsx
  translations/base.json
Labels: 🐞 bug

#2134 feat: connect Avalara to your organization
  package.json
  pnpm-lock.yaml
  src/components/settings/integrations/AddAvalaraDialog.tsx
  src/components/settings/integrations/AnrokIntegrationSettings.tsx
  src/components/settings/integrations/AvalaraIntegrationItemsList.tsx
  src/components/settings/integrations/AvalaraIntegrationItemsListAddons.tsx
  src/components/settings/integrations/AvalaraIntegrationItemsListBillableMetrics.tsx
  src/components/settings/integrations/AvalaraIntegrationItemsListDefault.tsx
  src/components/settings/integrations/AvalaraIntegrationMapItemDialog.tsx
  src/components/settings/integrations/AvalaraIntegrationSettings.tsx
  src/components/settings/integrations/DeleteAvalaraIntegrationDialog.tsx
  src/core/router/SettingRoutes.tsx
  src/core/utils/featureFlags.ts
  src/generated/graphql.tsx
  src/pages/settings/AvalaraIntegrationDetails.tsx
  src/pages/settings/AvalaraIntegrations.tsx
  src/pages/settings/Integrations.tsx
  src/public/images/avalara.svg
  translations/base.json
Labels: 🛠 feature

#2137 bug: refetch current orga on switch
  src/core/apolloClient/cacheUtils.ts
  src/core/apolloClient/init.ts
  src/core/constants/localStorageKeys.ts
  src/hooks/core/useLocationHistory.ts
  src/hooks/useCurrentUser.ts
  src/hooks/useOrganizationInfos.ts
  src/layouts/SideNavLayout.tsx
  src/pages/Analytics.tsx
  src/pages/Home.tsx
  src/pages/settings/CashfreeIntegrationDetails.tsx
Labels: 🐞 bug

#2142 feat: display all subscriptions
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/generated/graphql.tsx
Labels: 🌈 improvement

#2143 fix: clear filters nullish value
  src/components/designSystem/Filters/FiltersPanelPopper.tsx
Labels: 🐞 bug

#2140 fix: handle uppercased emails
  src/formValidation/initializeYup.ts
  src/pages/CustomerRequestOverduePayment/components/RequestPaymentForm.tsx
  src/pages/settings/Dunnings/CreateDunning.tsx
Labels: 🐞 bug

#2145 feat: connect user to Avalara tax provider
  src/components/customers/CustomerMainInfos.tsx
  src/components/customers/createCustomer/ExternalAppsAccordion/TaxProvidersAccordion.tsx
  src/components/customers/createCustomer/ExternalAppsAccordion/index.tsx
  src/components/customers/createCustomer/ExternalAppsAccordion/utils.ts
  src/components/settings/integrations/AvalaraIntegrationSettings.tsx
  src/core/constants/externalUrls.ts
  src/generated/graphql.tsx
  src/hooks/useCreateEditCustomer.ts
  translations/base.json
Labels: 🛠 feature

#2150 bug: make sure avalara data is populated in form if present
  src/pages/CreateCustomer.tsx
Labels: 🐞 bug

#2147 bug: fix wrong redirections
  src/hooks/core/useLocationHistory.ts
  src/pages/Home.tsx
  src/pages/Invitation.tsx
Labels: 🐞 bug

#2148 misc: make sure to build packages on install
  .gitignore
  package.json
Labels: 🔗 dependencies, 🌈 improvement

#2152 fix: add babel to jest
  babel.config.cjs
  jest.config.ts
  package.json
  pnpm-lock.yaml
Labels: 🌈 improvement

#2144 fix: improve copy to clipboard function
  src/core/utils/__tests__/copyToClipboard.test.ts
  src/core/utils/copyToClipboard.ts
  translations/base.json
Labels: 🐞 bug

#2153 misc: fix LS old data shape wrong access
  src/pages/Home.tsx
Labels: 🐞 bug

#2154 fix: dates with timezones
  src/pages/developers/ApiKeys.tsx
Labels: 🐞 bug

#2155 bug: prevent cache manipulation after deletion
  src/components/addOns/DeleteAddOnDialog.tsx
  src/components/customers/DeleteCustomerDialog.tsx
  src/components/plans/DeletePlanDialog.tsx
Labels: 🐞 bug

#2156 misc: fix and improve subscription details
  src/components/customers/overview/CustomerSubscriptionsList.tsx
  src/core/constants/statusSubscriptionMapping.ts
  src/pages/SubscriptionDetails.tsx
Labels: 🐞 bug, 🌈 improvement
