Repository getlago/lago-front, pull requests merged in 2025-03, with the labels that each got.

#2050 chore: fix CVE #93
  package.json
  yarn.lock
Labels: 🥷 chore, 🔗 dependencies

#2052 fix: support payment receipt created type on emails
  src/generated/graphql.tsx
  src/pages/settings/EmailSettings.tsx
Labels: 🐞 bug

#2051 refactor: pages migration
  src/components/customers/subscriptions/SubscriptionDatesOffsetHelperComponent.tsx
  src/pages/CreateAddOn.tsx
  src/pages/CreateBillableMetric.tsx
  src/pages/CreateCoupon.tsx
  src/pages/CreateInvoice.tsx
  src/pages/CreateSubscription.tsx
  src/pages/CustomerRequestOverduePayment/components/FreemiumAlert.tsx
  src/pages/CustomerRequestOverduePayment/components/RequestPaymentForm.tsx
  src/pages/CustomerRequestOverduePayment/index.tsx
  src/pages/Error404.tsx
  src/pages/Forbidden.tsx
  src/pages/Invitation.tsx
  src/pages/WalletForm/WalletForm.tsx
  src/pages/WalletForm/components/TopUpCard.tsx
  src/pages/auth/GoogleAuthCallback.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/OktaAuthCallback.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/SignUp.tsx
  src/pages/developers/Debugger.tsx
  src/pages/developers/WebhookLogs.tsx
  src/pages/settings/EmailScenarioConfig.tsx
  src/pages/settings/Members.tsx
  src/styles/designSystem/PageHeader.tsx
Labels: 🎨 UI

#2053 misc: add new filters for revenue streams
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/filtersElements/FiltersItemCountry.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemCustomerType.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemDate.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPlanCode.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemSubscription.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/utils.ts
  src/components/designSystem/graphs/MultipleLineChart.tsx
  src/generated/graphql.tsx
  translations/base.json
Labels: 🌈 improvement

#2054 misc: extract revenue sreams methods for testing
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/utils.ts
  src/components/designSystem/graphs/MultipleLineChart.tsx
  src/components/designSystem/graphs/__tests__/utils.test.ts
  src/components/designSystem/graphs/utils.ts
  src/generated/graphql.tsx
Labels: 🌈 improvement, 🧪 testing

#2058 feat: revamp create wallet and create topup layout
  src/components/layouts/CenteredPage.tsx
  src/components/wallets/CustomerWalletList.tsx
  src/components/wallets/TopupWalletDialog.tsx
  src/components/wallets/WalletAccordion.tsx
  src/components/wallets/WalletCodeSnippet.tsx
  src/components/wallets/WalletTransactionList.tsx
  src/components/wallets/__tests__/utils.test.ts
  src/components/wallets/utils.ts
  src/core/router/ObjectsRoutes.tsx
  src/generated/graphql.tsx
  src/pages/WalletForm/components/LoadingView.tsx
  src/pages/WalletForm/index.ts
  src/pages/wallet/CreateWallet.tsx
  src/pages/wallet/CreateWalletTopUp.tsx
  src/pages/wallet/components/SettingsSection.tsx
  src/pages/wallet/components/TopUpSection.tsx
  src/pages/wallet/form.ts
  src/pages/wallet/index.ts
  src/pages/wallet/types.ts
  translations/base.json
Labels: 🎨 UI

#2059 feat: add new avatar badge component
  src/components/designSystem/Avatar.tsx
  src/components/designSystem/Icon/Icon.tsx
  src/pages/__devOnly/DesignSystem.tsx
Labels: 🛠 feature

#2064 fix(paymentList): merge cache issue
  src/core/apolloClient/cache.ts
Labels: 🐞 bug

#2061 misc: format date correctly in table's header
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/utils.ts
Labels: 🌈 improvement

#2065 misc: move revenue streams overview logic into hook
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/analytics/useRevenueAnalyticsOverview.ts
  src/components/analytics/utils.ts
  src/generated/graphql.tsx
Labels: 🌈 improvement

#2067 bug: fix table action column shadow
  src/components/designSystem/Table/Table.tsx
  tailwind.config.ts
Labels: 🐞 bug

#2069 feat: add metadata and expiration date on wallet
  src/components/form/DatePicker/DatePicker.tsx
  src/formValidation/metadataSchema.ts
  src/generated/graphql.tsx
  src/pages/wallet/CreateWallet.tsx
  src/pages/wallet/CreateWalletTopUp.tsx
  src/pages/wallet/components/TopUpSection.tsx
  src/pages/wallet/form.ts
  translations/base.json
Labels: 🛠 feature

#2070 fix(datepicker): error message color
  src/components/form/DatePicker/DatePicker.tsx
Labels: 🐞 bug

#2071 misc: improve analytics perf and handle premium filters
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/analytics/RevenueStreamsStateContext.tsx
  src/components/analytics/__tests__/utils.test.ts
  src/components/analytics/useRevenueAnalyticsOverview.ts
  src/components/designSystem/Filters/FiltersPanelPopper.tsx
  src/components/designSystem/Filters/context.tsx
  src/components/designSystem/Popper.tsx
  src/components/designSystem/Table/HorizontalDataTable.tsx
  src/components/designSystem/graphs/MultipleLineChart.tsx
  src/pages/analytics/RevenueStreams.tsx
Labels: 🌈 improvement

#2073 misc(revenue-streams) ensure reset filters restores default currency
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/analytics/useRevenueAnalyticsOverview.ts
Labels: 🌈 improvement

#2074 misc(NavigationTab): allow to rely on tab index rather than url link
  src/components/designSystem/NavigationTab.tsx
Labels: 🌈 improvement

#2076 feat: add revenue stream plan and customer sections
  src/components/analytics/RevenueStreamsBreakdownSection.tsx
  src/components/analytics/RevenueStreamsCustomerBreakdownSection.tsx
  src/components/analytics/RevenueStreamsOverviewSection.tsx
  src/components/analytics/RevenueStreamsPlanBreakdownSection.tsx
  src/components/designSystem/Filters/types.ts
  src/components/designSystem/Filters/utils.ts
  src/core/constants/filters.ts
  src/generated/graphql.tsx
  src/pages/analytics/RevenueStreams.tsx
  translations/base.json
Labels: 🛠 feature

#2077 misc(multipleLineChart): Remove over optimisations that led to slow performances
  src/components/designSystem/graphs/MultipleLineChart.tsx
Labels: 🌈 improvement

#2075 misc: prevent showing anrok link on invoices with 0 fees
  src/generated/graphql.tsx
  src/pages/InvoiceOverview.tsx
Labels: 🌈 improvement

#2080 feat: release revenue streams new analytics dashboard
  src/components/analytics/__tests__/utils.test.ts
  src/components/analytics/revenueStreams/RevenueStreamsBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsCustomerBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsOverviewSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsPlanBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsStateContext.tsx
  src/components/analytics/revenueStreams/useRevenueAnalyticsOverview.ts
  src/components/analytics/revenueStreams/utils.ts
  src/components/designSystem/NavigationTab.tsx
  src/components/designSystem/Table/HorizontalDataTable.tsx
  src/components/designSystem/Table/Table.tsx
  src/components/designSystem/graphs/MultipleLineChart.tsx
  src/core/router/index.tsx
  src/generated/graphql.tsx
  src/hooks/usePermissions.ts
  src/layouts/SideNavLayout.tsx
  src/pages/Analytics.tsx
  src/pages/Home.tsx
  src/pages/OldAnalytics.tsx
  src/pages/analytics/NewAnalytics.tsx
  src/pages/analytics/RevenueStreams.tsx
  tailwind.config.ts
  translations/base.json
Labels: 🛠 feature

#2078 feat: wallet details
  src/components/wallets/CustomerWalletList.tsx
  src/components/wallets/WalletAccordion.tsx
  src/components/wallets/WalletDetailsDrawer.tsx
  src/components/wallets/WalletTransactionList.tsx
  src/components/wallets/WalletTransactionListItem/ListItem.tsx
  src/components/wallets/WalletTransactionListItem/__tests__/index.test.tsx
  src/components/wallets/WalletTransactionListItem/index.tsx
  src/generated/graphql.tsx
  src/main.css
  tailwind.config.ts
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend

#2082 refactor: invoices actions
  src/components/customers/CustomerInvoicesList.tsx
  src/components/invoices/InvoicesList.tsx
  src/hooks/usePermissionsInvoiceActions.ts
  src/pages/CustomerInvoiceDetails.tsx
Labels: 🌈 improvement

#2084 fix: add overdue column back in invoice list
  src/components/customers/CustomerInvoicesList.tsx
  src/components/invoices/InvoicesList.tsx
Labels: 🛠 feature

#2081 feat: add bcc emails field on dunning campaign
  src/generated/graphql.tsx
  src/hooks/useCreateEditDunningCampaign.ts
  src/pages/settings/Dunnings/CreateDunning.tsx
  translations/base.json
Labels: 🛠 feature, ⛔️ Need Backend, 👀 QA

#2087 deps: bump vite version to fix CVE #97
  package.json
  yarn.lock
Labels: 🔗 dependencies

#2089 bug(revenueStreams): remove forgotten yet-unexisting metadata
  src/generated/graphql.tsx
Labels: 🐞 bug

#2090 fix: terminated status on subscription page
  src/components/designSystem/Status.tsx
  src/components/subscriptions/SubscriptionDetailsOverview.tsx
  src/components/subscriptions/SubscriptionInformations.tsx
  src/components/subscriptions/SubscriptionUsageTabContent.tsx
  src/core/constants/statusSubscriptionMapping.ts
  src/pages/SubscriptionDetails.tsx
  translations/base.json
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nb.json
  translations/sv.json
Labels: 🐞 bug

#2091 misc(MRR): UX and behaviour improvement for graph and table
  src/components/analytics/AnalyticsStateContext.tsx
  src/components/analytics/mrr/MrrBreakdownSection.tsx
  src/components/analytics/mrr/MrrOverviewSection.tsx
  src/components/analytics/mrr/__tests__/utils.test.ts
  src/components/analytics/mrr/useMrrAnalyticsOverview.ts
  src/components/analytics/mrr/utils.ts
  src/components/customers/usage/CustomerUsage.tsx
  src/components/designSystem/Filters/utils.ts
  src/components/designSystem/graphs/AreaChart.tsx
  src/components/designSystem/graphs/MultipleLineChart.tsx
  src/generated/graphql.tsx
  src/pages/OldAnalytics.tsx
  translations/base.json
Labels: 🌈 improvement

#2092 misc: add pagination on analytics breakdown sections
  src/components/analytics/mrr/MrrBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsCustomerBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsPlanBreakdownSection.tsx
  src/core/apolloClient/cache.ts
  src/generated/graphql.tsx
Labels: 🌈 improvement

#2095 feat: add loading spinner in Home.tsx
  src/pages/Home.tsx
Labels: 🌈 improvement

#2094 feat: add link to invoices
  src/components/designSystem/Filters/utils.ts
  src/components/graphs/Invoices.tsx
  src/components/graphs/__tests__/Invoices.test.ts
Labels: 🌈 improvement

#2096 misc(Analytics): show deleted plans and customer with correct label
  src/components/analytics/mrr/MrrBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsCustomerBreakdownSection.tsx
  src/components/analytics/revenueStreams/RevenueStreamsPlanBreakdownSection.tsx
  src/components/designSystem/Filters/__tests__/utils.test.ts
  src/components/designSystem/Filters/filtersElements/FiltersItemCustomer.tsx
  src/components/designSystem/Filters/filtersElements/FiltersItemPlanCode.tsx
  src/components/designSystem/Filters/utils.ts
  src/generated/graphql.tsx
  translations/base.json
Labels: 🌈 improvement

#2098 misc: make sure we notify change on query invocation
  src/components/analytics/mrr/useMrrAnalyticsOverview.ts
  src/components/analytics/revenueStreams/useRevenueAnalyticsOverview.ts
  src/generated/graphql.tsx
Labels: 🌈 improvement

#2099 misc(mrr): display printable data on loading and empty results
  src/components/analytics/mrr/__tests__/utils.test.ts
  src/components/analytics/mrr/fixture.ts
  src/components/analytics/mrr/useMrrAnalyticsOverview.ts
Labels: 🌈 improvement
